max_map = {
    0x00: {
        "address": 0x00,
        "name": "SOFTWARE RESET",
        "R/W": "W",
        "expanded_bitfields": [
            "SWRESET",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
        ],
        "por state": 0x00,
    },
    0x01: {
        "address": 0x01,
        "name": "DEVICE STATUS",
        "R/W": "CoR",
        "expanded_bitfields": [
            "CLD",
            "SLD",
            "ULK",
            "",
            "",
            "JDET",
            "DRCACT",
            "DRCCLP",
        ],
        "por state": 0x00,
    },
    0x02: {
        "address": 0x02,
        "name": "JACK STATUS",
        "R/W": "R",
        "expanded_bitfields": [
            "",
            "",
            "",
            "",
            "",
            "LSNS",
            "JKSNS",
            "",
        ],
        "por state": 0x00,
    },
    0x03: {
        "address": 0x03,
        "name": "INTERUPT MASKS",
        "R/W": "R/W",
        "expanded_bitfields": [
            "ICLD",
            "ISLD",
            "IULK",
            "",
            "",
            "IJDET",
            "IDRCACT",
            "IDRCCLP",
        ],
        "por state": 0x04,
    },
    0x04: {
        "address": 0x04,
        "name": "SYSTEM CLOCK",
        "R/W": "W",
        "expanded_bitfields": [
            "26M",
            "19P2M",
            "13M",
            "12P288M",
            "12M",
            "11P2896M",
            "",
            "256FS",
        ],
        "por state": 0x00,
    },
    0x05: {
        "address": 0x05,
        "name": "SAMPLE RATE",
        "R/W": "W",
        "expanded_bitfields": [
            "",
            "",
            "SR_96K",
            "SR_32K",
            "SR_48K",
            "SR_44K1",
            "SR_16K",
            "SR_8K",
        ],
        "por state": 0x00,
    },
    0x06: {
        "address": 0x06,
        "name": "DAI INTERFACE",
        "R/W": "W",
        "expanded_bitfields": [
            "",
            "",
            "RJ_M",
            "RJ_S",
            "LJ_M",
            "LJ_S",
            "I2S_M",
            "I2S_S",
        ],
        "por state": 0x00,
    },
    0x07: {
        "address": 0x07,
        "name": "DAC PATH",
        "R/W": "W",
        "expanded_bitfields": [
            "DIG2_HP",
            "DIG2_ EAR",
            "DIG2_ SPK",
            "DIG2_ LOUT",
            "",
            "",
            "",
            "",
        ],
        "por state": 0x00,
    },
    0x08: {
        "address": 0x08,
        "name": "MIC/DIRECT TO ADC",
        "R/W": "W",
        "expanded_bitfields": [
            "IN12_MIC1",
            "IN34_ MIC2",
            "",
            "",
            "IN12_ DADC",
            "IN34_ DADC",
            "IN56_ DADC",
            "",
        ],
        "por state": 0x00,
    },
    0x09: {
        "address": 0x09,
        "name": "LINE TO ADC",
        "R/W": "W",
        "expanded_bitfields": [
            "IN12S_AB",
            "IN34S_AB",
            "IN56S_AB",
            "IN34D_A",
            "IN65D_B",
            "",
            "",
            "",
        ],
        "por state": 0x00,
    },
    0x0A: {
        "address": 0x0A,
        "name": "ANALOG MIC LOOP",
        "R/W": "W",
        "expanded_bitfields": [
            "IN12_ M1HPL",
            "IN12_ M1SPKL",
            "IN12_ M1EAR",
            "IN12_ M1LOUTL",
            "IN34_ M2HPR",
            "IN34_ M2SPKR",
            "IN34_ M2EAR",
            "IN34_ M2LOUTR",
        ],
        "por state": 0x00,
    },
    0x0B: {
        "address": 0x0B,
        "name": "ANALOG LINE LOOP",
        "R/W": "W",
        "expanded_bitfields": [
            "IN12S_ ABHP",
            "IN34D_ ASPKL",
            "IN34D_ AEAR",
            "IN12S_ ABLOUT",
            "IN34S_ ABHP",
            "IN65D _BSPKR",
            "IN65D_ BEAR",
            "IN34S_ ABLOUT",
        ],
        "por state": 0x00,
    },
    0x0C: {
        "address": 0x0C,
        "name": "RESERVED",
        "R/W": "",
        "expanded_bitfields": [
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
        ],
        "por state": 0x00,
    },
    0x0D: {
        "address": 0x0D,
        "name": "LINE INPUT CONFIG",
        "R/W": "R/W",
        "expanded_bitfields": [
            "IN34DIFF",
            "IN65DIFF",
            "IN1SEEN",
            "IN2SEEN",
            "IN3SEEN",
            "IN4SEEN",
            "IN5SEEN",
            "IN6SEEN",
        ],
        "por state": 0x00,
    },
    0x0E: {
        "address": 0x0E,
        "name": "LINE INPUT LEVEL",
        "R/W": "R/W",
        "expanded_bitfields": [
            "MIXG135",
            "MIXG246",
            "LINAPGA[2:0]",
            "LINAPGA[2:0]",
            "LINAPGA[2:0]",
            "LINBPGA[2:0]",
            "LINBPGA[2:0]",
            "LINBPGA[2:0]",
        ],
        "por state": 0x1B,
    },
    0x0F: {
        "address": 0x0F,
        "name": "INPUT MODE",
        "R/W": "R/W",
        "expanded_bitfields": [
            "EXTBUFA",
            "EXTBUFB",
            "",
            "",
            "",
            "",
            "EXT_MIC[1:0]",
            "EXT_MIC[1:0]",
        ],
        "por state": 0x00,
    },
    0x10: {
        "address": 0x10,
        "name": "MIC1 INPUT LEVEL",
        "R/W": "R/W",
        "expanded_bitfields": [
            "",
            "PA1EN[1:0]",
            "PA1EN[1:0]",
            "PGAM1[4:0]",
            "PGAM1[4:0]",
            "PGAM1[4:0]",
            "PGAM1[4:0]",
            "PGAM1[4:0]",
        ],
        "por state": 0x14,
    },
    0x11: {
        "address": 0x11,
        "name": "MIC2 INPUT LEVEL",
        "R/W": "R/W",
        "expanded_bitfields": [
            "",
            "PA2EN[1:0]",
            "PA2EN[1:0]",
            "PGAM2[4:0]",
            "PGAM2[4:0]",
            "PGAM2[4:0]",
            "PGAM2[4:0]",
            "PGAM2[4:0]",
        ],
        "por state": 0x14,
    },
    0x12: {
        "address": 0x12,
        "name": "MIC BIAS VOLTAGE",
        "R/W": "R/W",
        "expanded_bitfields": [
            "",
            "",
            "",
            "",
            "",
            "",
            "MBVSEL[1:0]",
            "MBVSEL[1:0]",
        ],
        "por state": 0x00,
    },
    0x13: {
        "address": 0x13,
        "name": "DIGITAL MIC ENABLE",
        "R/W": "R/W",
        "expanded_bitfields": [
            "",
            "DMICCLK[2:0]",
            "DMICCLK[2:0]",
            "DMICCLK[2:0]",
            "DIGMIC2R",
            "DIGMIC2L",
            "DIGMIC1R",
            "DIGMIC1L",
        ],
        "por state": 0x00,
    },
    0x14: {
        "address": 0x14,
        "name": "DIGITAL MIC CONFIG",
        "R/W": "R/W",
        "expanded_bitfields": [
            "DMIC_COMP[3:0]",
            "DMIC_COMP[3:0]",
            "DMIC_COMP[3:0]",
            "DMIC_COMP[3:0]",
            "",
            "",
            "DMIC_FREQ[1:0]",
            "",
        ],
        "por state": 0x00,
    },
    0x15: {
        "address": 0x15,
        "name": "LEFT ADC MIXER",
        "R/W": "R/W",
        "expanded_bitfields": [
            "",
            "MIXADL[6:0]",
            "MIXADL[6:0]",
            "MIXADL[6:0]",
            "MIXADL[6:0]",
            "MIXADL[6:0]",
            "MIXADL[6:0]",
            "MIXADL[6:0]",
        ],
        "por state": 0x00,
    },
    0x16: {
        "address": 0x16,
        "name": "RIGHT ADC MIXER",
        "R/W": "R/W",
        "expanded_bitfields": [
            "",
            "MIXADR[6:0]",
            "MIXADR[6:0]",
            "MIXADR[6:0]",
            "MIXADR[6:0]",
            "MIXADR[6:0]",
            "MIXADR[6:0]",
            "MIXADR[6:0]",
        ],
        "por state": 0x00,
    },
    0x17: {
        "address": 0x17,
        "name": "LEFT RECORD LEVEL",
        "R/W": "R/W",
        "expanded_bitfields": [
            "",
            "AVLG[2:0]",
            "AVLG[2:0]",
            "AVLG[2:0]",
            "AVL[3:0]",
            "AVL[3:0]",
            "AVL[3:0]",
            "AVL[3:0]",
        ],
        "por state": 0x03,
    },
    0x18: {
        "address": 0x18,
        "name": "RIGHT RECORD LEVEL",
        "R/W": "R/W",
        "expanded_bitfields": [
            "",
            "AVRG[2:0]",
            "AVRG[2:0]",
            "AVRG[2:0]",
            "AVR[3:0]",
            "AVR[3:0]",
            "AVR[3:0]",
            "AVR[3:0]",
        ],
        "por state": 0x03,
    },
    0x19: {
        "address": 0x19,
        "name": "RECORD BIQUAD LEVEL",
        "R/W": "R/W",
        "expanded_bitfields": [
            "",
            "",
            "",
            "",
            "AVBQ[3:0]",
            "AVBQ[3:0]",
            "AVBQ[3:0]",
            "AVBQ[3:0]",
        ],
        "por state": 0x00,
    },
    0x1A: {
        "address": 0x1A,
        "name": "RECORD SIDETONE",
        "R/W": "R/W",
        "expanded_bitfields": [
            "DSTS[1:0]",
            "DSTS[1:0]",
            "",
            "DVST[4:0]",
            "DVST[4:0]",
            "DVST[4:0]",
            "DVST[4:0]",
            "DVST[4:0]",
        ],
        "por state": 0x00,
    },
    0x1B: {
        "address": 0x1B,
        "name": "SYSTEM CLOCK",
        "R/W": "R/W",
        "expanded_bitfields": [
            "",
            "",
            "PSCLK[1:0]",
            "PSCLK[1:0]",
            "",
            "",
            "",
            "",
        ],
        "por state": 0x00,
    },
    0x1C: {
        "address": 0x1C,
        "name": "CLOCK MODE",
        "R/W": "R/W",
        "expanded_bitfields": [
            "FREQ[3:0]",
            "FREQ[3:0]",
            "FREQ[3:0]",
            "FREQ[3:0]",
            "",
            "",
            "",
            "USE_MI",
        ],
        "por state": 0x00,
    },
    0x1D: {
        "address": 0x1D,
        "name": "CLOCK RATIO NI MSB",
        "R/W": "R/W",
        "expanded_bitfields": [
            "",
            "NI[14:8]",
            "NI[14:8]",
            "NI[14:8]",
            "NI[14:8]",
            "NI[14:8]",
            "NI[14:8]",
            "NI[14:8]",
        ],
        "por state": 0x00,
    },
    0x1E: {
        "address": 0x1E,
        "name": "CLOCK RATIO NI LSB",
        "R/W": "R/W",
        "expanded_bitfields": [
            "NI[7:0]",
            "NI[7:0]",
            "NI[7:0]",
            "NI[7:0]",
            "NI[7:0]",
            "NI[7:0]",
            "NI[7:0]",
            "NI[7:0]",
        ],
        "por state": 0x00,
    },
    0x1F: {
        "address": 0x1F,
        "name": "CLOCK RATIO MI MSB",
        "R/W": "R/W",
        "expanded_bitfields": [
            "MI[15:8]",
            "MI[15:8]",
            "MI[15:8]",
            "MI[15:8]",
            "MI[15:8]",
            "MI[15:8]",
            "MI[15:8]",
            "MI[15:8]",
        ],
        "por state": 0x00,
    },
    0x20: {
        "address": 0x20,
        "name": "CLOCK RATIO MI LSB",
        "R/W": "R/W",
        "expanded_bitfields": [
            "MI[7:0]",
            "MI[7:0]",
            "MI[7:0]",
            "MI[7:0]",
            "MI[7:0]",
            "MI[7:0]",
            "MI[7:0]",
            "MI[7:0]",
        ],
        "por state": 0x00,
    },
    0x21: {
        "address": 0x21,
        "name": "MASTER MODE",
        "R/W": "R/W",
        "expanded_bitfields": [
            "MAS",
            "",
            "",
            "",
            "",
            "BSEL[2:0]",
            "BSEL[2:0]",
            "BSEL[2:0]",
        ],
        "por state": 0x00,
    },
    0x22: {
        "address": 0x22,
        "name": "INTERFACE FORMAT",
        "R/W": "R/W",
        "expanded_bitfields": [
            "",
            "",
            "RJ",
            "WCI",
            "BCI",
            "DLY",
            "WS[1:0]",
            "WS[1:0]",
        ],
        "por state": 0x00,
    },
    0x23: {
        "address": 0x23,
        "name": "TDM CONTROL",
        "R/W": "R/W",
        "expanded_bitfields": [
            "",
            "",
            "",
            "",
            "",
            "",
            "FSW",
            "TDM",
        ],
        "por state": 0x00,
    },
    0x24: {
        "address": 0x24,
        "name": "TDM FORMAT",
        "R/W": "R/W",
        "expanded_bitfields": [
            "SLOTL[1:0]",
            "SLOTL[1:0]",
            "SLOTR[1:0]",
            "SLOTR[1:0]",
            "SLOTDLY[3:0]",
            "SLOTDLY[3:0]",
            "SLOTDLY[3:0]",
            "SLOTDLY[3:0]",
        ],
        "por state": 0x00,
    },
    0x25: {
        "address": 0x25,
        "name": "I/O CONFIGURATION",
        "R/W": "R/W",
        "expanded_bitfields": [
            "",
            "",
            "LTEN",
            "LBEN",
            "DMONO",
            "HIZOFF",
            "SDOEN",
            "SDIEN",
        ],
        "por state": 0x00,
    },
    0x26: {
        "address": 0x26,
        "name": "FILTER CONFIGURATION",
        "R/W": "R/W",
        "expanded_bitfields": [
            "MODE",
            "AHPF",
            "DHPF",
            "DHF",
            "DMIC2_ MODE",
            "DMIC2_ HPF",
            "",
            "",
        ],
        "por state": 0x88,
    },
    0x27: {
        "address": 0x27,
        "name": "DAI PLAYBACK LEVEL",
        "R/W": "R/W",
        "expanded_bitfields": [
            "DVM",
            "",
            "DVG[1:0]",
            "DVG[1:0]",
            "DV[3:0]",
            "DV[3:0]",
            "DV[3:0]",
            "DV[3:0]",
        ],
        "por state": 0x00,
    },
    0x28: {
        "address": 0x28,
        "name": "EQ PLAYBACK LEVEL",
        "R/W": "R/W",
        "expanded_bitfields": [
            "",
            "",
            "",
            "EQCLP",
            "DVEQ[3:0]",
            "DVEQ[3:0]",
            "DVEQ[3:0]",
            "DVEQ[3:0]",
        ],
        "por state": 0x00,
    },
    0x29: {
        "address": 0x29,
        "name": "LEFT HP MIXER",
        "R/W": "R/W",
        "expanded_bitfields": [
            "",
            "",
            "MIXHPL[5:0]",
            "MIXHPL[5:0]",
            "MIXHPL[5:0]",
            "MIXHPL[5:0]",
            "MIXHPL[5:0]",
            "MIXHPL[5:0]",
        ],
        "por state": 0x00,
    },
    0x2A: {
        "address": 0x2A,
        "name": "RIGHT HP MIXER",
        "R/W": "R/W",
        "expanded_bitfields": [
            "",
            "",
            "MIXHPR[5:0]",
            "MIXHPR[5:0]",
            "MIXHPR[5:0]",
            "MIXHPR[5:0]",
            "MIXHPR[5:0]",
            "MIXHPR[5:0]",
        ],
        "por state": 0x00,
    },
    0x2B: {
        "address": 0x2B,
        "name": "HP CONTROL",
        "R/W": "R/W",
        "expanded_bitfields": [
            "",
            "",
            "MIXHP RSEL",
            "MIXHP LSEL",
            "MIXHPRG[1:0]",
            "MIXHPRG[1:0]",
            "MIXHPLG[1:0]",
            "MIXHPLG[1:0]",
        ],
        "por state": 0x00,
    },
    0x2C: {
        "address": 0x2C,
        "name": "LEFT HP VOLUME",
        "R/W": "R/W",
        "expanded_bitfields": [ # 0b00000111, HPLM: 0b1 0x01
            "HPLM",
            "",
            "",
            "HPVOLL[4:0]",
            "HPVOLL[4:0]",
            "HPVOLL[4:0]",
            "HPVOLL[4:0]",
            "HPVOLL[4:0]",
        ],
        "por state": 0x1A,
    },
    0x2D: {
        "address": 0x2D,
        "name": "RIGHT HP VOLUME",
        "R/W": "R/W",
        "expanded_bitfields": [
            "HPRM",
            "",
            "",
            "HPVOLR[4:0]",
            "HPVOLR[4:0]",
            "HPVOLR[4:0]",
            "HPVOLR[4:0]",
            "HPVOLR[4:0]",
        ],
        "por state": 0x1A,
    },
    0x2E: {
        "address": 0x2E,
        "name": "LEFT SPK MIXER",
        "R/W": "R/W",
        "expanded_bitfields": [
            "",
            "",
            "MIXSPL[5:0]",
            "MIXSPL[5:0]",
            "MIXSPL[5:0]",
            "MIXSPL[5:0]",
            "MIXSPL[5:0]",
            "MIXSPL[5:0]",
        ],
        "por state": 0x00,
    },
    0x2F: {
        "address": 0x2F,
        "name": "RIGHT SPK MIXER",
        "R/W": "R/W",
        "expanded_bitfields": [
            "",
            "SPK_ SLAVE",
            "MIXSPR[5:0]",
            "MIXSPR[5:0]",
            "MIXSPR[5:0]",
            "MIXSPR[5:0]",
            "MIXSPR[5:0]",
            "MIXSPR[5:0]",
        ],
        "por state": 0x00,
    },
    0x30: {
        "address": 0x30,
        "name": "SPK CONTROL",
        "R/W": "R/W",
        "expanded_bitfields": [
            "",
            "",
            "",
            "",
            "MIXSPRG[1:0]",
            "MIXSPRG[1:0]",
            "MIXSPLG[1:0]",
            "MIXSPLG[1:0]",
        ],
        "por state": 0x00,
    },
    0x31: {
        "address": 0x31,
        "name": "LEFT SPK VOLUME",
        "R/W": "R/W",
        "expanded_bitfields": [
            "SPLM",
            "",
            "SPVOLL[5:0]",
            "SPVOLL[5:0]",
            "SPVOLL[5:0]",
            "SPVOLL[5:0]",
            "SPVOLL[5:0]",
            "SPVOLL[5:0]",
        ],
        "por state": 0x2C,
    },
    0x32: {
        "address": 0x32,
        "name": "RIGHT SPK VOLUME",
        "R/W": "R/W",
        "expanded_bitfields": [
            "SPRM",
            "",
            "SPVOLR[5:0]",
            "SPVOLR[5:0]",
            "SPVOLR[5:0]",
            "SPVOLR[5:0]",
            "SPVOLR[5:0]",
            "SPVOLR[5:0]",
        ],
        "por state": 0x2C,
    },
    0x33: {
        "address": 0x33,
        "name": "DRC TIMING",
        "R/W": "R/W",
        "expanded_bitfields": [
            "DRCEN",
            "DRCRLS[2:0]",
            "DRCRLS[2:0]",
            "DRCRLS[2:0]",
            "",
            "DRCATK[2:0]",
            "DRCATK[2:0]",
            "DRCATK[2:0]",
        ],
        "por state": 0x00,
    },
    0x34: {
        "address": 0x34,
        "name": "DRC COMPRESSOR",
        "R/W": "R/W",
        "expanded_bitfields": [
            "DRCCMP[2:0]",
            "DRCCMP[2:0]",
            "DRCCMP[2:0]",
            "DRCTHC[4:0]",
            "DRCTHC[4:0]",
            "DRCTHC[4:0]",
            "DRCTHC[4:0]",
            "DRCTHC[4:0]",
        ],
        "por state": 0x00,
    },
    0x35: {
        "address": 0x35,
        "name": "DRC EXPANDER",
        "R/W": "R/W",
        "expanded_bitfields": [
            "DRCEXP[2:0]",
            "DRCEXP[2:0]",
            "DRCEXP[2:0]",
            "DRCTHE[4:0]",
            "DRCTHE[4:0]",
            "DRCTHE[4:0]",
            "DRCTHE[4:0]",
            "DRCTHE[4:0]",
        ],
        "por state": 0x00,
    },
    0x36: {
        "address": 0x36,
        "name": "DRC GAIN",
        "R/W": "R/W",
        "expanded_bitfields": [
            "",
            "",
            "",
            "DRCG[4:0]",
            "DRCG[4:0]",
            "DRCG[4:0]",
            "DRCG[4:0]",
            "DRCG[4:0]",
        ],
        "por state": 0x00,
    },
    0x37: {
        "address": 0x37,
        "name": "RCV/LOUTL MIXER",
        "R/W": "R/W",
        "expanded_bitfields": [
            "",
            "",
            "MIXRCVL[5:0]",
            "MIXRCVL[5:0]",
            "MIXRCVL[5:0]",
            "MIXRCVL[5:0]",
            "MIXRCVL[5:0]",
            "MIXRCVL[5:0]",
        ],
        "por state": 0x00,
    },
    0x38: {
        "address": 0x38,
        "name": "RCV/LOUTL CONTROL",
        "R/W": "R/W",
        "expanded_bitfields": [
            "",
            "",
            "",
            "",
            "",
            "",
            "MIXRCVLG[1:0]",
            "MIXRCVLG[1:0]",
        ],
        "por state": 0x00,
    },
    0x39: {
        "address": 0x39,
        "name": "RCV/LOUTL VOLUME",
        "R/W": "R/W",
        "expanded_bitfields": [
            "RCVLM",
            "",
            "",
            "RCVLVOL[4:0]",
            "RCVLVOL[4:0]",
            "RCVLVOL[4:0]",
            "RCVLVOL[4:0]",
            "RCVLVOL[4:0]",
        ],
        "por state": 0x15,
    },
    0x3A: {
        "address": 0x3A,
        "name": "LOUTR MIXER",
        "R/W": "R/W",
        "expanded_bitfields": [
            "LINMOD",
            "",
            "MIXRCVR[5:0]",
            "MIXRCVR[5:0]",
            "MIXRCVR[5:0]",
            "MIXRCVR[5:0]",
            "MIXRCVR[5:0]",
            "MIXRCVR[5:0]",
        ],
        "por state": 0x00,
    },
    0x3B: {
        "address": 0x3B,
        "name": "LOUTR CONTROL",
        "R/W": "R/W",
        "expanded_bitfields": [
            "",
            "",
            "",
            "",
            "",
            "",
            "MIXRCVRG[1:0]",
            "MIXRCVRG[1:0]",
        ],
        "por state": 0x00,
    },
    0x3C: {
        "address": 0x3C,
        "name": "LOUTR VOLUME",
        "R/W": "R/W",
        "expanded_bitfields": [
            "RCVRM",
            "",
            "",
            "RCVRVOL[4:0]",
            "RCVRVOL[4:0]",
            "RCVRVOL[4:0]",
            "RCVRVOL[4:0]",
            "RCVRVOL[4:0]",
        ],
        "por state": 0x15,
    },
    0x3D: {
        "address": 0x3D,
        "name": "JACK DETECT",
        "R/W": "R/W",
        "expanded_bitfields": [
            "JDETEN",
            "JDWK",
            "",
            "",
            "",
            "",
            "JDEB[1:0]",
            "JDEB[1:0]",
        ],
        "por state": 0x00,
    },
    0x3E: {
        "address": 0x3E,
        "name": "INPUT ENABLE",
        "R/W": "R/W",
        "expanded_bitfields": [
            "",
            "",
            "",
            "MBEN",
            "LINEAEN",
            "LINEBEN",
            "ADREN",
            "ADLEN",
        ],
        "por state": 0x00,
    },
    0x3F: {
        "address": 0x3F,
        "name": "OUTPUT ENABLE",
        "R/W": "R/W",
        "expanded_bitfields": [
            "HPREN",
            "HPLEN",
            "SPREN",
            "SPLEN",
            "RCVLEN",
            "RCVREN",
            "DAREN",
            "DALEN",
        ],
        "por state": 0x00,
    },
    0x40: {
        "address": 0x40,
        "name": "ZCD/SLEW CONTROL",
        "R/W": "R/W",
        "expanded_bitfields": [
            "",
            "",
            "",
            "",
            "",
            "ZDEN",
            "VS2EN",
            "VSEN",
        ],
        "por state": 0x00,
    },
    0x41: {
        "address": 0x41,
        "name": "DSP FILTER ENABLE",
        "R/W": "R/W",
        "expanded_bitfields": [
            "",
            "",
            "",
            "DMIC2BQ EN",
            "RECBQEN",
            "EQ3BAND EN",
            "EQ5BAND EN",
            "EQ7BAND EN",
        ],
        "por state": 0x00,
    },
    0x42: {
        "address": 0x42,
        "name": "BIAS CONTROL",
        "R/W": "R/W",
        "expanded_bitfields": [
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "BIAS_ MODE",
        ],
        "por state": 0x00,
    },
    0x43: {
        "address": 0x43,
        "name": "DAC CONTROL",
        "R/W": "R/W",
        "expanded_bitfields": [
            "",
            "",
            "",
            "",
            "",
            "",
            "PERF MODE",
            "DACHP",
        ],
        "por state": 0x00,
    },
    0x44: {
        "address": 0x44,
        "name": "ADC CONTROL",
        "R/W": "R/W",
        "expanded_bitfields": [
            "",
            "",
            "",
            "",
            "",
            "OSR128",
            "ADC DITHER",
            "ADCHP",
        ],
        "por state": 0x06,
    },
    0x45: {
        "address": 0x45,
        "name": "DEVICE SHUTDOWN",
        "R/W": "R/W",
        "expanded_bitfields": [
            "SHDN",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
        ],
        "por state": 0x00,
    },
    0x46: {
        "address": 0x46,
        "name": "EQUALIZER BAND 1 COEFFICIENT B0",
        "R/W": "R/W",
        "expanded_bitfields": [
            "B0_1[23:16]",
            "B0_1[23:16]",
            "B0_1[23:16]",
            "B0_1[23:16]",
            "B0_1[23:16]",
            "B0_1[23:16]",
            "B0_1[23:16]",
            "B0_1[23:16]",
        ],
        "por state": "",
    },
    0x47: {
        "address": 0x47,
        "name": "EQUALIZER BAND 1 COEFFICIENT B0",
        "R/W": "R/W",
        "expanded_bitfields": [
            "B0_1[15:8]",
            "B0_1[15:8]",
            "B0_1[15:8]",
            "B0_1[15:8]",
            "B0_1[15:8]",
            "B0_1[15:8]",
            "B0_1[15:8]",
            "B0_1[15:8]",
        ],
        "por state": "",
    },
    0x48: {
        "address": 0x48,
        "name": "EQUALIZER BAND 1 COEFFICIENT B0",
        "R/W": "R/W",
        "expanded_bitfields": [
            "B0_1[7:0]",
            "B0_1[7:0]",
            "B0_1[7:0]",
            "B0_1[7:0]",
            "B0_1[7:0]",
            "B0_1[7:0]",
            "B0_1[7:0]",
            "B0_1[7:0]",
        ],
        "por state": "",
    },
    0x49: {
        "address": 0x49,
        "name": "EQUALIZER BAND 1 COEFFICIENT B1",
        "R/W": "R/W",
        "expanded_bitfields": [
            "B1_1[23:16]",
            "B1_1[23:16]",
            "B1_1[23:16]",
            "B1_1[23:16]",
            "B1_1[23:16]",
            "B1_1[23:16]",
            "B1_1[23:16]",
            "B1_1[23:16]",
        ],
        "por state": "",
    },
    0x4A: {
        "address": 0x4A,
        "name": "EQUALIZER BAND 1 COEFFICIENT B1",
        "R/W": "R/W",
        "expanded_bitfields": [
            "B1_1[15:8]",
            "B1_1[15:8]",
            "B1_1[15:8]",
            "B1_1[15:8]",
            "B1_1[15:8]",
            "B1_1[15:8]",
            "B1_1[15:8]",
            "B1_1[15:8]",
        ],
        "por state": "",
    },
    0x4B: {
        "address": 0x4B,
        "name": "EQUALIZER BAND 1 COEFFICIENT B1",
        "R/W": "R/W",
        "expanded_bitfields": [
            "B1_1[7:0]",
            "B1_1[7:0]",
            "B1_1[7:0]",
            "B1_1[7:0]",
            "B1_1[7:0]",
            "B1_1[7:0]",
            "B1_1[7:0]",
            "B1_1[7:0]",
        ],
        "por state": "",
    },
    0x4C: {
        "address": 0x4C,
        "name": "EQUALIZER BAND 1 COEFFICIENT B2",
        "R/W": "R/W",
        "expanded_bitfields": [
            "B2_1[23:16]",
            "B2_1[23:16]",
            "B2_1[23:16]",
            "B2_1[23:16]",
            "B2_1[23:16]",
            "B2_1[23:16]",
            "B2_1[23:16]",
            "B2_1[23:16]",
        ],
        "por state": "",
    },
    0x4D: {
        "address": 0x4D,
        "name": "EQUALIZER BAND 1 COEFFICIENT B2",
        "R/W": "R/W",
        "expanded_bitfields": [
            "B2_1[15:8]",
            "B2_1[15:8]",
            "B2_1[15:8]",
            "B2_1[15:8]",
            "B2_1[15:8]",
            "B2_1[15:8]",
            "B2_1[15:8]",
            "B2_1[15:8]",
        ],
        "por state": "",
    },
    0x4E: {
        "address": 0x4E,
        "name": "EQUALIZER BAND 1 COEFFICIENT B2",
        "R/W": "R/W",
        "expanded_bitfields": [
            "B2_1[7:0]",
            "B2_1[7:0]",
            "B2_1[7:0]",
            "B2_1[7:0]",
            "B2_1[7:0]",
            "B2_1[7:0]",
            "B2_1[7:0]",
            "B2_1[7:0]",
        ],
        "por state": "",
    },
    0x4F: {
        "address": 0x4F,
        "name": "EQUALIZER BAND 1 COEFFICIENT A1",
        "R/W": "R/W",
        "expanded_bitfields": [
            "A1_1[23:16]",
            "A1_1[23:16]",
            "A1_1[23:16]",
            "A1_1[23:16]",
            "A1_1[23:16]",
            "A1_1[23:16]",
            "A1_1[23:16]",
            "A1_1[23:16]",
        ],
        "por state": "",
    },
    0x50: {
        "address": 0x50,
        "name": "EQUALIZER BAND 1 COEFFICIENT A1",
        "R/W": "R/W",
        "expanded_bitfields": [
            "A1_1[15:8]",
            "A1_1[15:8]",
            "A1_1[15:8]",
            "A1_1[15:8]",
            "A1_1[15:8]",
            "A1_1[15:8]",
            "A1_1[15:8]",
            "A1_1[15:8]",
        ],
        "por state": "",
    },
    0x51: {
        "address": 0x51,
        "name": "EQUALIZER BAND 1 COEFFICIENT A1",
        "R/W": "R/W",
        "expanded_bitfields": [
            "A1_1[7:0]",
            "A1_1[7:0]",
            "A1_1[7:0]",
            "A1_1[7:0]",
            "A1_1[7:0]",
            "A1_1[7:0]",
            "A1_1[7:0]",
            "A1_1[7:0]",
        ],
        "por state": "",
    },
    0x52: {
        "address": 0x52,
        "name": "EQUALIZER BAND 1 COEFFICIENT A2",
        "R/W": "R/W",
        "expanded_bitfields": [
            "A2_1[23:16]",
            "A2_1[23:16]",
            "A2_1[23:16]",
            "A2_1[23:16]",
            "A2_1[23:16]",
            "A2_1[23:16]",
            "A2_1[23:16]",
            "A2_1[23:16]",
        ],
        "por state": "",
    },
    0x53: {
        "address": 0x53,
        "name": "EQUALIZER BAND 1 COEFFICIENT A2",
        "R/W": "R/W",
        "expanded_bitfields": [
            "A2_1[15:8]",
            "A2_1[15:8]",
            "A2_1[15:8]",
            "A2_1[15:8]",
            "A2_1[15:8]",
            "A2_1[15:8]",
            "A2_1[15:8]",
            "A2_1[15:8]",
        ],
        "por state": "",
    },
    0x54: {
        "address": 0x54,
        "name": "EQUALIZER BAND 1 COEFFICIENT A2",
        "R/W": "R/W",
        "expanded_bitfields": [
            "A2_1[7:0]",
            "A2_1[7:0]",
            "A2_1[7:0]",
            "A2_1[7:0]",
            "A2_1[7:0]",
            "A2_1[7:0]",
            "A2_1[7:0]",
            "A2_1[7:0]",
        ],
        "por state": "",
    },
    0x55: {
        "address": 0x55,
        "name": "EQUALIZER BAND 2 COEFFICIENT B0",
        "R/W": "R/W",
        "expanded_bitfields": [
            "B0_2[23:16]",
            "B0_2[23:16]",
            "B0_2[23:16]",
            "B0_2[23:16]",
            "B0_2[23:16]",
            "B0_2[23:16]",
            "B0_2[23:16]",
            "B0_2[23:16]",
        ],
        "por state": "",
    },
    0x56: {
        "address": 0x56,
        "name": "EQUALIZER BAND 2 COEFFICIENT B0",
        "R/W": "R/W",
        "expanded_bitfields": [
            "B0_2[15:8]",
            "B0_2[15:8]",
            "B0_2[15:8]",
            "B0_2[15:8]",
            "B0_2[15:8]",
            "B0_2[15:8]",
            "B0_2[15:8]",
            "B0_2[15:8]",
        ],
        "por state": "",
    },
    0x57: {
        "address": 0x57,
        "name": "EQUALIZER BAND 2 COEFFICIENT B0",
        "R/W": "R/W",
        "expanded_bitfields": [
            "B0_2[7:0]",
            "B0_2[7:0]",
            "B0_2[7:0]",
            "B0_2[7:0]",
            "B0_2[7:0]",
            "B0_2[7:0]",
            "B0_2[7:0]",
            "B0_2[7:0]",
        ],
        "por state": "",
    },
    0x58: {
        "address": 0x58,
        "name": "EQUALIZER BAND 2 COEFFICIENT B1",
        "R/W": "R/W",
        "expanded_bitfields": [
            "B1_2[23:16]",
            "B1_2[23:16]",
            "B1_2[23:16]",
            "B1_2[23:16]",
            "B1_2[23:16]",
            "B1_2[23:16]",
            "B1_2[23:16]",
            "B1_2[23:16]",
        ],
        "por state": "",
    },
    0x59: {
        "address": 0x59,
        "name": "EQUALIZER BAND 2 COEFFICIENT B1",
        "R/W": "R/W",
        "expanded_bitfields": [
            "B1_2[15:8]",
            "B1_2[15:8]",
            "B1_2[15:8]",
            "B1_2[15:8]",
            "B1_2[15:8]",
            "B1_2[15:8]",
            "B1_2[15:8]",
            "B1_2[15:8]",
        ],
        "por state": "",
    },
    0x5A: {
        "address": 0x5A,
        "name": "EQUALIZER BAND 2 COEFFICIENT B1",
        "R/W": "R/W",
        "expanded_bitfields": [
            "B1_2[7:0]",
            "B1_2[7:0]",
            "B1_2[7:0]",
            "B1_2[7:0]",
            "B1_2[7:0]",
            "B1_2[7:0]",
            "B1_2[7:0]",
            "B1_2[7:0]",
        ],
        "por state": "",
    },
    0x5B: {
        "address": 0x5B,
        "name": "EQUALIZER BAND 2 COEFFICIENT B2",
        "R/W": "R/W",
        "expanded_bitfields": [
            "B2_2[23:16]",
            "B2_2[23:16]",
            "B2_2[23:16]",
            "B2_2[23:16]",
            "B2_2[23:16]",
            "B2_2[23:16]",
            "B2_2[23:16]",
            "B2_2[23:16]",
        ],
        "por state": "",
    },
    0x5C: {
        "address": 0x5C,
        "name": "EQUALIZER BAND 2 COEFFICIENT B2",
        "R/W": "R/W",
        "expanded_bitfields": [
            "B2_2[15:8]",
            "B2_2[15:8]",
            "B2_2[15:8]",
            "B2_2[15:8]",
            "B2_2[15:8]",
            "B2_2[15:8]",
            "B2_2[15:8]",
            "B2_2[15:8]",
        ],
        "por state": "",
    },
    0x5D: {
        "address": 0x5D,
        "name": "EQUALIZER BAND 2 COEFFICIENT B2",
        "R/W": "R/W",
        "expanded_bitfields": [
            "B2_2[7:0]",
            "B2_2[7:0]",
            "B2_2[7:0]",
            "B2_2[7:0]",
            "B2_2[7:0]",
            "B2_2[7:0]",
            "B2_2[7:0]",
            "B2_2[7:0]",
        ],
        "por state": "",
    },
    0x5E: {
        "address": 0x5E,
        "name": "EQUALIZER BAND 2 COEFFICIENT A1",
        "R/W": "R/W",
        "expanded_bitfields": [
            "A1_2[23:16]",
            "A1_2[23:16]",
            "A1_2[23:16]",
            "A1_2[23:16]",
            "A1_2[23:16]",
            "A1_2[23:16]",
            "A1_2[23:16]",
            "A1_2[23:16]",
        ],
        "por state": "",
    },
    0x5F: {
        "address": 0x5F,
        "name": "EQUALIZER BAND 2 COEFFICIENT A1",
        "R/W": "R/W",
        "expanded_bitfields": [
            "A1_2[15:8]",
            "A1_2[15:8]",
            "A1_2[15:8]",
            "A1_2[15:8]",
            "A1_2[15:8]",
            "A1_2[15:8]",
            "A1_2[15:8]",
            "A1_2[15:8]",
        ],
        "por state": "",
    },
    0x60: {
        "address": 0x60,
        "name": "EQUALIZER BAND 2 COEFFICIENT A1",
        "R/W": "R/W",
        "expanded_bitfields": [
            "A1_2[7:0]",
            "A1_2[7:0]",
            "A1_2[7:0]",
            "A1_2[7:0]",
            "A1_2[7:0]",
            "A1_2[7:0]",
            "A1_2[7:0]",
            "A1_2[7:0]",
        ],
        "por state": "",
    },
    0x61: {
        "address": 0x61,
        "name": "EQUALIZER BAND 2 COEFFICIENT A2",
        "R/W": "R/W",
        "expanded_bitfields": [
            "A2_2[23:16]",
            "A2_2[23:16]",
            "A2_2[23:16]",
            "A2_2[23:16]",
            "A2_2[23:16]",
            "A2_2[23:16]",
            "A2_2[23:16]",
            "A2_2[23:16]",
        ],
        "por state": "",
    },
    0x62: {
        "address": 0x62,
        "name": "EQUALIZER BAND 2 COEFFICIENT A2",
        "R/W": "R/W",
        "expanded_bitfields": [
            "A2_2[15:8]",
            "A2_2[15:8]",
            "A2_2[15:8]",
            "A2_2[15:8]",
            "A2_2[15:8]",
            "A2_2[15:8]",
            "A2_2[15:8]",
            "A2_2[15:8]",
        ],
        "por state": "",
    },
    0x63: {
        "address": 0x63,
        "name": "EQUALIZER BAND 2 COEFFICIENT A2",
        "R/W": "R/W",
        "expanded_bitfields": [
            "A2_2[7:0]",
            "A2_2[7:0]",
            "A2_2[7:0]",
            "A2_2[7:0]",
            "A2_2[7:0]",
            "A2_2[7:0]",
            "A2_2[7:0]",
            "A2_2[7:0]",
        ],
        "por state": "",
    },
    0x64: {
        "address": 0x64,
        "name": "EQUALIZER BAND 3 COEFFICIENT B0",
        "R/W": "R/W",
        "expanded_bitfields": [
            "B0_3[23:16]",
            "B0_3[23:16]",
            "B0_3[23:16]",
            "B0_3[23:16]",
            "B0_3[23:16]",
            "B0_3[23:16]",
            "B0_3[23:16]",
            "B0_3[23:16]",
        ],
        "por state": "",
    },
    0x65: {
        "address": 0x65,
        "name": "EQUALIZER BAND 3 COEFFICIENT B0",
        "R/W": "R/W",
        "expanded_bitfields": [
            "B0_3[15:8]",
            "B0_3[15:8]",
            "B0_3[15:8]",
            "B0_3[15:8]",
            "B0_3[15:8]",
            "B0_3[15:8]",
            "B0_3[15:8]",
            "B0_3[15:8]",
        ],
        "por state": "",
    },
    0x66: {
        "address": 0x66,
        "name": "EQUALIZER BAND 3 COEFFICIENT B0",
        "R/W": "R/W",
        "expanded_bitfields": [
            "B0_3[7:0]",
            "B0_3[7:0]",
            "B0_3[7:0]",
            "B0_3[7:0]",
            "B0_3[7:0]",
            "B0_3[7:0]",
            "B0_3[7:0]",
            "B0_3[7:0]",
        ],
        "por state": "",
    },
    0x67: {
        "address": 0x67,
        "name": "EQUALIZER BAND 3 COEFFICIENT B1",
        "R/W": "R/W",
        "expanded_bitfields": [
            "B1_3[23:16]",
            "B1_3[23:16]",
            "B1_3[23:16]",
            "B1_3[23:16]",
            "B1_3[23:16]",
            "B1_3[23:16]",
            "B1_3[23:16]",
            "B1_3[23:16]",
        ],
        "por state": "",
    },
    0x68: {
        "address": 0x68,
        "name": "EQUALIZER BAND 3 COEFFICIENT B1",
        "R/W": "R/W",
        "expanded_bitfields": [
            "B1_3[15:8]",
            "B1_3[15:8]",
            "B1_3[15:8]",
            "B1_3[15:8]",
            "B1_3[15:8]",
            "B1_3[15:8]",
            "B1_3[15:8]",
            "B1_3[15:8]",
        ],
        "por state": "",
    },
    0x69: {
        "address": 0x69,
        "name": "EQUALIZER BAND 3 COEFFICIENT B1",
        "R/W": "R/W",
        "expanded_bitfields": [
            "B1_3[7:0]",
            "B1_3[7:0]",
            "B1_3[7:0]",
            "B1_3[7:0]",
            "B1_3[7:0]",
            "B1_3[7:0]",
            "B1_3[7:0]",
            "B1_3[7:0]",
        ],
        "por state": "",
    },
    0x6A: {
        "address": 0x6A,
        "name": "EQUALIZER BAND 3 COEFFICIENT B2",
        "R/W": "R/W",
        "expanded_bitfields": [
            "B2_3[23:16]",
            "B2_3[23:16]",
            "B2_3[23:16]",
            "B2_3[23:16]",
            "B2_3[23:16]",
            "B2_3[23:16]",
            "B2_3[23:16]",
            "B2_3[23:16]",
        ],
        "por state": "",
    },
    0x6B: {
        "address": 0x6B,
        "name": "EQUALIZER BAND 3 COEFFICIENT B2",
        "R/W": "R/W",
        "expanded_bitfields": [
            "B2_3[15:8]",
            "B2_3[15:8]",
            "B2_3[15:8]",
            "B2_3[15:8]",
            "B2_3[15:8]",
            "B2_3[15:8]",
            "B2_3[15:8]",
            "B2_3[15:8]",
        ],
        "por state": "",
    },
    0x6C: {
        "address": 0x6C,
        "name": "EQUALIZER BAND 3 COEFFICIENT B2",
        "R/W": "R/W",
        "expanded_bitfields": [
            "B2_3[7:0]",
            "B2_3[7:0]",
            "B2_3[7:0]",
            "B2_3[7:0]",
            "B2_3[7:0]",
            "B2_3[7:0]",
            "B2_3[7:0]",
            "B2_3[7:0]",
        ],
        "por state": "",
    },
    0x6D: {
        "address": 0x6D,
        "name": "EQUALIZER BAND 3 COEFFICIENT A1",
        "R/W": "R/W",
        "expanded_bitfields": [
            "A1_3[23:16]",
            "A1_3[23:16]",
            "A1_3[23:16]",
            "A1_3[23:16]",
            "A1_3[23:16]",
            "A1_3[23:16]",
            "A1_3[23:16]",
            "A1_3[23:16]",
        ],
        "por state": "",
    },
    0x6E: {
        "address": 0x6E,
        "name": "EQUALIZER BAND 3 COEFFICIENT A1",
        "R/W": "R/W",
        "expanded_bitfields": [
            "A1_3[15:8]",
            "A1_3[15:8]",
            "A1_3[15:8]",
            "A1_3[15:8]",
            "A1_3[15:8]",
            "A1_3[15:8]",
            "A1_3[15:8]",
            "A1_3[15:8]",
        ],
        "por state": "",
    },
    0x6F: {
        "address": 0x6F,
        "name": "EQUALIZER BAND 3 COEFFICIENT A1",
        "R/W": "R/W",
        "expanded_bitfields": [
            "A1_3[7:0]",
            "A1_3[7:0]",
            "A1_3[7:0]",
            "A1_3[7:0]",
            "A1_3[7:0]",
            "A1_3[7:0]",
            "A1_3[7:0]",
            "A1_3[7:0]",
        ],
        "por state": "",
    },
    0x70: {
        "address": 0x70,
        "name": "EQUALIZER BAND 3 COEFFICIENT A2",
        "R/W": "R/W",
        "expanded_bitfields": [
            "A2_3[23:16]",
            "A2_3[23:16]",
            "A2_3[23:16]",
            "A2_3[23:16]",
            "A2_3[23:16]",
            "A2_3[23:16]",
            "A2_3[23:16]",
            "A2_3[23:16]",
        ],
        "por state": "",
    },
    0x71: {
        "address": 0x71,
        "name": "EQUALIZER BAND 3 COEFFICIENT A2",
        "R/W": "R/W",
        "expanded_bitfields": [
            "A2_3[15:8]",
            "A2_3[15:8]",
            "A2_3[15:8]",
            "A2_3[15:8]",
            "A2_3[15:8]",
            "A2_3[15:8]",
            "A2_3[15:8]",
            "A2_3[15:8]",
        ],
        "por state": "",
    },
    0x72: {
        "address": 0x72,
        "name": "EQUALIZER BAND 3 COEFFICIENT A2",
        "R/W": "R/W",
        "expanded_bitfields": [
            "A2_3[7:0]",
            "A2_3[7:0]",
            "A2_3[7:0]",
            "A2_3[7:0]",
            "A2_3[7:0]",
            "A2_3[7:0]",
            "A2_3[7:0]",
            "A2_3[7:0]",
        ],
        "por state": "",
    },
    0x73: {
        "address": 0x73,
        "name": "EQUALIZER BAND 4 COEFFICIENT B0",
        "R/W": "R/W",
        "expanded_bitfields": [
            "B0_4[23:16]",
            "B0_4[23:16]",
            "B0_4[23:16]",
            "B0_4[23:16]",
            "B0_4[23:16]",
            "B0_4[23:16]",
            "B0_4[23:16]",
            "B0_4[23:16]",
        ],
        "por state": "",
    },
    0x74: {
        "address": 0x74,
        "name": "EQUALIZER BAND 4 COEFFICIENT B0",
        "R/W": "R/W",
        "expanded_bitfields": [
            "B0_4[15:8]",
            "B0_4[15:8]",
            "B0_4[15:8]",
            "B0_4[15:8]",
            "B0_4[15:8]",
            "B0_4[15:8]",
            "B0_4[15:8]",
            "B0_4[15:8]",
        ],
        "por state": "",
    },
    0x75: {
        "address": 0x75,
        "name": "EQUALIZER BAND 4 COEFFICIENT B0",
        "R/W": "R/W",
        "expanded_bitfields": [
            "B0_4[7:0]",
            "B0_4[7:0]",
            "B0_4[7:0]",
            "B0_4[7:0]",
            "B0_4[7:0]",
            "B0_4[7:0]",
            "B0_4[7:0]",
            "B0_4[7:0]",
        ],
        "por state": "",
    },
    0x76: {
        "address": 0x76,
        "name": "EQUALIZER BAND 4 COEFFICIENT B1",
        "R/W": "R/W",
        "expanded_bitfields": [
            "B1_4[23:16]",
            "B1_4[23:16]",
            "B1_4[23:16]",
            "B1_4[23:16]",
            "B1_4[23:16]",
            "B1_4[23:16]",
            "B1_4[23:16]",
            "B1_4[23:16]",
        ],
        "por state": "",
    },
    0x77: {
        "address": 0x77,
        "name": "EQUALIZER BAND 4 COEFFICIENT B1",
        "R/W": "R/W",
        "expanded_bitfields": [
            "B1_4[15:8]",
            "B1_4[15:8]",
            "B1_4[15:8]",
            "B1_4[15:8]",
            "B1_4[15:8]",
            "B1_4[15:8]",
            "B1_4[15:8]",
            "B1_4[15:8]",
        ],
        "por state": "",
    },
    0x78: {
        "address": 0x78,
        "name": "EQUALIZER BAND 4 COEFFICIENT B1",
        "R/W": "R/W",
        "expanded_bitfields": [
            "B1_4[7:0]",
            "B1_4[7:0]",
            "B1_4[7:0]",
            "B1_4[7:0]",
            "B1_4[7:0]",
            "B1_4[7:0]",
            "B1_4[7:0]",
            "B1_4[7:0]",
        ],
        "por state": "",
    },
    0x79: {
        "address": 0x79,
        "name": "EQUALIZER BAND 4 COEFFICIENT B2",
        "R/W": "R/W",
        "expanded_bitfields": [
            "B2_4[23:16]",
            "B2_4[23:16]",
            "B2_4[23:16]",
            "B2_4[23:16]",
            "B2_4[23:16]",
            "B2_4[23:16]",
            "B2_4[23:16]",
            "B2_4[23:16]",
        ],
        "por state": "",
    },
    0x7A: {
        "address": 0x7A,
        "name": "EQUALIZER BAND 4 COEFFICIENT B2",
        "R/W": "R/W",
        "expanded_bitfields": [
            "B2_4[15:8]",
            "B2_4[15:8]",
            "B2_4[15:8]",
            "B2_4[15:8]",
            "B2_4[15:8]",
            "B2_4[15:8]",
            "B2_4[15:8]",
            "B2_4[15:8]",
        ],
        "por state": "",
    },
    0x7B: {
        "address": 0x7B,
        "name": "EQUALIZER BAND 4 COEFFICIENT B2",
        "R/W": "R/W",
        "expanded_bitfields": [
            "B2_4[7:0]",
            "B2_4[7:0]",
            "B2_4[7:0]",
            "B2_4[7:0]",
            "B2_4[7:0]",
            "B2_4[7:0]",
            "B2_4[7:0]",
            "B2_4[7:0]",
        ],
        "por state": "",
    },
    0x7C: {
        "address": 0x7C,
        "name": "EQUALIZER BAND 4 COEFFICIENT A1",
        "R/W": "R/W",
        "expanded_bitfields": [
            "A1_4[23:16]",
            "A1_4[23:16]",
            "A1_4[23:16]",
            "A1_4[23:16]",
            "A1_4[23:16]",
            "A1_4[23:16]",
            "A1_4[23:16]",
            "A1_4[23:16]",
        ],
        "por state": "",
    },
    0x7D: {
        "address": 0x7D,
        "name": "EQUALIZER BAND 4 COEFFICIENT A1",
        "R/W": "R/W",
        "expanded_bitfields": [
            "A1_4[15:8]",
            "A1_4[15:8]",
            "A1_4[15:8]",
            "A1_4[15:8]",
            "A1_4[15:8]",
            "A1_4[15:8]",
            "A1_4[15:8]",
            "A1_4[15:8]",
        ],
        "por state": "",
    },
    0x7E: {
        "address": 0x7E,
        "name": "EQUALIZER BAND 4 COEFFICIENT A1",
        "R/W": "R/W",
        "expanded_bitfields": [
            "A1_4[7:0]",
            "A1_4[7:0]",
            "A1_4[7:0]",
            "A1_4[7:0]",
            "A1_4[7:0]",
            "A1_4[7:0]",
            "A1_4[7:0]",
            "A1_4[7:0]",
        ],
        "por state": "",
    },
    0x7F: {
        "address": 0x7F,
        "name": "EQUALIZER BAND 4 COEFFICIENT A2",
        "R/W": "R/W",
        "expanded_bitfields": [
            "A2_4[23:16]",
            "A2_4[23:16]",
            "A2_4[23:16]",
            "A2_4[23:16]",
            "A2_4[23:16]",
            "A2_4[23:16]",
            "A2_4[23:16]",
            "A2_4[23:16]",
        ],
        "por state": "",
    },
    0x80: {
        "address": 0x80,
        "name": "EQUALIZER BAND 4 COEFFICIENT A2",
        "R/W": "R/W",
        "expanded_bitfields": [
            "A2_4[15:8]",
            "A2_4[15:8]",
            "A2_4[15:8]",
            "A2_4[15:8]",
            "A2_4[15:8]",
            "A2_4[15:8]",
            "A2_4[15:8]",
            "A2_4[15:8]",
        ],
        "por state": "",
    },
    0x81: {
        "address": 0x81,
        "name": "EQUALIZER BAND 4 COEFFICIENT A2",
        "R/W": "R/W",
        "expanded_bitfields": [
            "A2_4[7:0]",
            "A2_4[7:0]",
            "A2_4[7:0]",
            "A2_4[7:0]",
            "A2_4[7:0]",
            "A2_4[7:0]",
            "A2_4[7:0]",
            "A2_4[7:0]",
        ],
        "por state": "",
    },
    0x82: {
        "address": 0x82,
        "name": "EQUALIZER BAND 5 COEFFICIENT B0",
        "R/W": "R/W",
        "expanded_bitfields": [
            "B0_5[23:16]",
            "B0_5[23:16]",
            "B0_5[23:16]",
            "B0_5[23:16]",
            "B0_5[23:16]",
            "B0_5[23:16]",
            "B0_5[23:16]",
            "B0_5[23:16]",
        ],
        "por state": "",
    },
    0x83: {
        "address": 0x83,
        "name": "EQUALIZER BAND 5 COEFFICIENT B0",
        "R/W": "R/W",
        "expanded_bitfields": [
            "B0_5[15:8]",
            "B0_5[15:8]",
            "B0_5[15:8]",
            "B0_5[15:8]",
            "B0_5[15:8]",
            "B0_5[15:8]",
            "B0_5[15:8]",
            "B0_5[15:8]",
        ],
        "por state": "",
    },
    0x84: {
        "address": 0x84,
        "name": "EQUALIZER BAND 5 COEFFICIENT B0",
        "R/W": "R/W",
        "expanded_bitfields": [
            "B0_5[7:0]",
            "B0_5[7:0]",
            "B0_5[7:0]",
            "B0_5[7:0]",
            "B0_5[7:0]",
            "B0_5[7:0]",
            "B0_5[7:0]",
            "B0_5[7:0]",
        ],
        "por state": "",
    },
    0x85: {
        "address": 0x85,
        "name": "EQUALIZER BAND 5 COEFFICIENT B1",
        "R/W": "R/W",
        "expanded_bitfields": [
            "B1_5[23:16]",
            "B1_5[23:16]",
            "B1_5[23:16]",
            "B1_5[23:16]",
            "B1_5[23:16]",
            "B1_5[23:16]",
            "B1_5[23:16]",
            "B1_5[23:16]",
        ],
        "por state": "",
    },
    0x86: {
        "address": 0x86,
        "name": "EQUALIZER BAND 5 COEFFICIENT B1",
        "R/W": "R/W",
        "expanded_bitfields": [
            "B1_5[15:8]",
            "B1_5[15:8]",
            "B1_5[15:8]",
            "B1_5[15:8]",
            "B1_5[15:8]",
            "B1_5[15:8]",
            "B1_5[15:8]",
            "B1_5[15:8]",
        ],
        "por state": "",
    },
    0x87: {
        "address": 0x87,
        "name": "EQUALIZER BAND 5 COEFFICIENT B1",
        "R/W": "R/W",
        "expanded_bitfields": [
            "B1_5[7:0]",
            "B1_5[7:0]",
            "B1_5[7:0]",
            "B1_5[7:0]",
            "B1_5[7:0]",
            "B1_5[7:0]",
            "B1_5[7:0]",
            "B1_5[7:0]",
        ],
        "por state": "",
    },
    0x88: {
        "address": 0x88,
        "name": "EQUALIZER BAND 5 COEFFICIENT B2",
        "R/W": "R/W",
        "expanded_bitfields": [
            "B2_5[23:16]",
            "B2_5[23:16]",
            "B2_5[23:16]",
            "B2_5[23:16]",
            "B2_5[23:16]",
            "B2_5[23:16]",
            "B2_5[23:16]",
            "B2_5[23:16]",
        ],
        "por state": "",
    },
    0x89: {
        "address": 0x89,
        "name": "EQUALIZER BAND 5 COEFFICIENT B2",
        "R/W": "R/W",
        "expanded_bitfields": [
            "B2_5[15:8]",
            "B2_5[15:8]",
            "B2_5[15:8]",
            "B2_5[15:8]",
            "B2_5[15:8]",
            "B2_5[15:8]",
            "B2_5[15:8]",
            "B2_5[15:8]",
        ],
        "por state": "",
    },
    0x8A: {
        "address": 0x8A,
        "name": "EQUALIZER BAND 5 COEFFICIENT B2",
        "R/W": "R/W",
        "expanded_bitfields": [
            "B2_5[7:0]",
            "B2_5[7:0]",
            "B2_5[7:0]",
            "B2_5[7:0]",
            "B2_5[7:0]",
            "B2_5[7:0]",
            "B2_5[7:0]",
            "B2_5[7:0]",
        ],
        "por state": "",
    },
    0x8B: {
        "address": 0x8B,
        "name": "EQUALIZER BAND 5 COEFFICIENT A1",
        "R/W": "R/W",
        "expanded_bitfields": [
            "A1_5[23:16]",
            "A1_5[23:16]",
            "A1_5[23:16]",
            "A1_5[23:16]",
            "A1_5[23:16]",
            "A1_5[23:16]",
            "A1_5[23:16]",
            "A1_5[23:16]",
        ],
        "por state": "",
    },
    0x8C: {
        "address": 0x8C,
        "name": "EQUALIZER BAND 5 COEFFICIENT A1",
        "R/W": "R/W",
        "expanded_bitfields": [
            "A1_5[15:8]",
            "A1_5[15:8]",
            "A1_5[15:8]",
            "A1_5[15:8]",
            "A1_5[15:8]",
            "A1_5[15:8]",
            "A1_5[15:8]",
            "A1_5[15:8]",
        ],
        "por state": "",
    },
    0x8D: {
        "address": 0x8D,
        "name": "EQUALIZER BAND 5 COEFFICIENT A1",
        "R/W": "R/W",
        "expanded_bitfields": [
            "A1_5[7:0]",
            "A1_5[7:0]",
            "A1_5[7:0]",
            "A1_5[7:0]",
            "A1_5[7:0]",
            "A1_5[7:0]",
            "A1_5[7:0]",
            "A1_5[7:0]",
        ],
        "por state": "",
    },
    0x8E: {
        "address": 0x8E,
        "name": "EQUALIZER BAND 5 COEFFICIENT A2",
        "R/W": "R/W",
        "expanded_bitfields": [
            "A2_5[23:16]",
            "A2_5[23:16]",
            "A2_5[23:16]",
            "A2_5[23:16]",
            "A2_5[23:16]",
            "A2_5[23:16]",
            "A2_5[23:16]",
            "A2_5[23:16]",
        ],
        "por state": "",
    },
    0x8F: {
        "address": 0x8F,
        "name": "EQUALIZER BAND 5 COEFFICIENT A2",
        "R/W": "R/W",
        "expanded_bitfields": [
            "A2_5[15:8]",
            "A2_5[15:8]",
            "A2_5[15:8]",
            "A2_5[15:8]",
            "A2_5[15:8]",
            "A2_5[15:8]",
            "A2_5[15:8]",
            "A2_5[15:8]",
        ],
        "por state": "",
    },
    0x90: {
        "address": 0x90,
        "name": "EQUALIZER BAND 5 COEFFICIENT A2",
        "R/W": "R/W",
        "expanded_bitfields": [
            "A2_5[7:0]",
            "A2_5[7:0]",
            "A2_5[7:0]",
            "A2_5[7:0]",
            "A2_5[7:0]",
            "A2_5[7:0]",
            "A2_5[7:0]",
            "A2_5[7:0]",
        ],
        "por state": "",
    },
    0x91: {
        "address": 0x91,
        "name": "EQUALIZER BAND 6 COEFFICIENT B0",
        "R/W": "R/W",
        "expanded_bitfields": [
            "B0_6[23:16]",
            "B0_6[23:16]",
            "B0_6[23:16]",
            "B0_6[23:16]",
            "B0_6[23:16]",
            "B0_6[23:16]",
            "B0_6[23:16]",
            "B0_6[23:16]",
        ],
        "por state": "",
    },
    0x92: {
        "address": 0x92,
        "name": "EQUALIZER BAND 6 COEFFICIENT B0",
        "R/W": "R/W",
        "expanded_bitfields": [
            "B0_6[15:8]",
            "B0_6[15:8]",
            "B0_6[15:8]",
            "B0_6[15:8]",
            "B0_6[15:8]",
            "B0_6[15:8]",
            "B0_6[15:8]",
            "B0_6[15:8]",
        ],
        "por state": "",
    },
    0x93: {
        "address": 0x93,
        "name": "EQUALIZER BAND 6 COEFFICIENT B0",
        "R/W": "R/W",
        "expanded_bitfields": [
            "B0_6[7:0]",
            "B0_6[7:0]",
            "B0_6[7:0]",
            "B0_6[7:0]",
            "B0_6[7:0]",
            "B0_6[7:0]",
            "B0_6[7:0]",
            "B0_6[7:0]",
        ],
        "por state": "",
    },
    0x94: {
        "address": 0x94,
        "name": "EQUALIZER BAND 6 COEFFICIENT B1",
        "R/W": "R/W",
        "expanded_bitfields": [
            "B1_6[23:16]",
            "B1_6[23:16]",
            "B1_6[23:16]",
            "B1_6[23:16]",
            "B1_6[23:16]",
            "B1_6[23:16]",
            "B1_6[23:16]",
            "B1_6[23:16]",
        ],
        "por state": "",
    },
    0x95: {
        "address": 0x95,
        "name": "EQUALIZER BAND 6 COEFFICIENT B1",
        "R/W": "R/W",
        "expanded_bitfields": [
            "B1_6[15:8]",
            "B1_6[15:8]",
            "B1_6[15:8]",
            "B1_6[15:8]",
            "B1_6[15:8]",
            "B1_6[15:8]",
            "B1_6[15:8]",
            "B1_6[15:8]",
        ],
        "por state": "",
    },
    0x96: {
        "address": 0x96,
        "name": "EQUALIZER BAND 6 COEFFICIENT B1",
        "R/W": "R/W",
        "expanded_bitfields": [
            "B1_6[7:0]",
            "B1_6[7:0]",
            "B1_6[7:0]",
            "B1_6[7:0]",
            "B1_6[7:0]",
            "B1_6[7:0]",
            "B1_6[7:0]",
            "B1_6[7:0]",
        ],
        "por state": "",
    },
    0x97: {
        "address": 0x97,
        "name": "EQUALIZER BAND 6 COEFFICIENT B2",
        "R/W": "R/W",
        "expanded_bitfields": [
            "B2_6[23:16]",
            "B2_6[23:16]",
            "B2_6[23:16]",
            "B2_6[23:16]",
            "B2_6[23:16]",
            "B2_6[23:16]",
            "B2_6[23:16]",
            "B2_6[23:16]",
        ],
        "por state": "",
    },
    0x98: {
        "address": 0x98,
        "name": "EQUALIZER BAND 6 COEFFICIENT B2",
        "R/W": "R/W",
        "expanded_bitfields": [
            "B2_6[15:8]",
            "B2_6[15:8]",
            "B2_6[15:8]",
            "B2_6[15:8]",
            "B2_6[15:8]",
            "B2_6[15:8]",
            "B2_6[15:8]",
            "B2_6[15:8]",
        ],
        "por state": "",
    },
    0x99: {
        "address": 0x99,
        "name": "EQUALIZER BAND 6 COEFFICIENT B2",
        "R/W": "R/W",
        "expanded_bitfields": [
            "B2_6[7:0]",
            "B2_6[7:0]",
            "B2_6[7:0]",
            "B2_6[7:0]",
            "B2_6[7:0]",
            "B2_6[7:0]",
            "B2_6[7:0]",
            "B2_6[7:0]",
        ],
        "por state": "",
    },
    0x9A: {
        "address": 0x9A,
        "name": "EQUALIZER BAND 6 COEFFICIENT A1",
        "R/W": "R/W",
        "expanded_bitfields": [
            "A1_6[23:16]",
            "A1_6[23:16]",
            "A1_6[23:16]",
            "A1_6[23:16]",
            "A1_6[23:16]",
            "A1_6[23:16]",
            "A1_6[23:16]",
            "A1_6[23:16]",
        ],
        "por state": "",
    },
    0x9B: {
        "address": 0x9B,
        "name": "EQUALIZER BAND 6 COEFFICIENT A1",
        "R/W": "R/W",
        "expanded_bitfields": [
            "A1_6[15:8]",
            "A1_6[15:8]",
            "A1_6[15:8]",
            "A1_6[15:8]",
            "A1_6[15:8]",
            "A1_6[15:8]",
            "A1_6[15:8]",
            "A1_6[15:8]",
        ],
        "por state": "",
    },
    0x9C: {
        "address": 0x9C,
        "name": "EQUALIZER BAND 6 COEFFICIENT A1",
        "R/W": "R/W",
        "expanded_bitfields": [
            "A1_6[7:0]",
            "A1_6[7:0]",
            "A1_6[7:0]",
            "A1_6[7:0]",
            "A1_6[7:0]",
            "A1_6[7:0]",
            "A1_6[7:0]",
            "A1_6[7:0]",
        ],
        "por state": "",
    },
    0x9D: {
        "address": 0x9D,
        "name": "EQUALIZER BAND 6 COEFFICIENT A2",
        "R/W": "R/W",
        "expanded_bitfields": [
            "A2_6[23:16]",
            "A2_6[23:16]",
            "A2_6[23:16]",
            "A2_6[23:16]",
            "A2_6[23:16]",
            "A2_6[23:16]",
            "A2_6[23:16]",
            "A2_6[23:16]",
        ],
        "por state": "",
    },
    0x9E: {
        "address": 0x9E,
        "name": "EQUALIZER BAND 6 COEFFICIENT A2",
        "R/W": "R/W",
        "expanded_bitfields": [
            "A2_6[15:8]",
            "A2_6[15:8]",
            "A2_6[15:8]",
            "A2_6[15:8]",
            "A2_6[15:8]",
            "A2_6[15:8]",
            "A2_6[15:8]",
            "A2_6[15:8]",
        ],
        "por state": "",
    },
    0x9F: {
        "address": 0x9F,
        "name": "EQUALIZER BAND 6 COEFFICIENT A2",
        "R/W": "R/W",
        "expanded_bitfields": [
            "A2_6[7:0]",
            "A2_6[7:0]",
            "A2_6[7:0]",
            "A2_6[7:0]",
            "A2_6[7:0]",
            "A2_6[7:0]",
            "A2_6[7:0]",
            "A2_6[7:0]",
        ],
        "por state": "",
    },
    0xA0: {
        "address": 0xA0,
        "name": "EQUALIZER BAND 7 COEFFICIENT B0",
        "R/W": "R/W",
        "expanded_bitfields": [
            "B0_7[23:16]",
            "B0_7[23:16]",
            "B0_7[23:16]",
            "B0_7[23:16]",
            "B0_7[23:16]",
            "B0_7[23:16]",
            "B0_7[23:16]",
            "B0_7[23:16]",
        ],
        "por state": "",
    },
    0xA1: {
        "address": 0xA1,
        "name": "EQUALIZER BAND 7 COEFFICIENT B0",
        "R/W": "R/W",
        "expanded_bitfields": [
            "B0_7[15:8]",
            "B0_7[15:8]",
            "B0_7[15:8]",
            "B0_7[15:8]",
            "B0_7[15:8]",
            "B0_7[15:8]",
            "B0_7[15:8]",
            "B0_7[15:8]",
        ],
        "por state": "",
    },
    0xA2: {
        "address": 0xA2,
        "name": "EQUALIZER BAND 7 COEFFICIENT B0",
        "R/W": "R/W",
        "expanded_bitfields": [
            "B0_7[7:0]",
            "B0_7[7:0]",
            "B0_7[7:0]",
            "B0_7[7:0]",
            "B0_7[7:0]",
            "B0_7[7:0]",
            "B0_7[7:0]",
            "B0_7[7:0]",
        ],
        "por state": "",
    },
    0xA3: {
        "address": 0xA3,
        "name": "EQUALIZER BAND 7 COEFFICIENT B1",
        "R/W": "R/W",
        "expanded_bitfields": [
            "B1_7[23:16]",
            "B1_7[23:16]",
            "B1_7[23:16]",
            "B1_7[23:16]",
            "B1_7[23:16]",
            "B1_7[23:16]",
            "B1_7[23:16]",
            "B1_7[23:16]",
        ],
        "por state": "",
    },
    0xA4: {
        "address": 0xA4,
        "name": "EQUALIZER BAND 7 COEFFICIENT B1",
        "R/W": "R/W",
        "expanded_bitfields": [
            "B1_7[15:8]",
            "B1_7[15:8]",
            "B1_7[15:8]",
            "B1_7[15:8]",
            "B1_7[15:8]",
            "B1_7[15:8]",
            "B1_7[15:8]",
            "B1_7[15:8]",
        ],
        "por state": "",
    },
    0xA5: {
        "address": 0xA5,
        "name": "EQUALIZER BAND 7 COEFFICIENT B1",
        "R/W": "R/W",
        "expanded_bitfields": [
            "B1_7[7:0]",
            "B1_7[7:0]",
            "B1_7[7:0]",
            "B1_7[7:0]",
            "B1_7[7:0]",
            "B1_7[7:0]",
            "B1_7[7:0]",
            "B1_7[7:0]",
        ],
        "por state": "",
    },
    0xA6: {
        "address": 0xA6,
        "name": "EQUALIZER BAND 7 COEFFICIENT B2",
        "R/W": "R/W",
        "expanded_bitfields": [
            "B2_7[23:16]",
            "B2_7[23:16]",
            "B2_7[23:16]",
            "B2_7[23:16]",
            "B2_7[23:16]",
            "B2_7[23:16]",
            "B2_7[23:16]",
            "B2_7[23:16]",
        ],
        "por state": "",
    },
    0xA7: {
        "address": 0xA7,
        "name": "EQUALIZER BAND 7 COEFFICIENT B2",
        "R/W": "R/W",
        "expanded_bitfields": [
            "B2_7[15:8]",
            "B2_7[15:8]",
            "B2_7[15:8]",
            "B2_7[15:8]",
            "B2_7[15:8]",
            "B2_7[15:8]",
            "B2_7[15:8]",
            "B2_7[15:8]",
        ],
        "por state": "",
    },
    0xA8: {
        "address": 0xA8,
        "name": "EQUALIZER BAND 7 COEFFICIENT B2",
        "R/W": "R/W",
        "expanded_bitfields": [
            "B2_7[7:0]",
            "B2_7[7:0]",
            "B2_7[7:0]",
            "B2_7[7:0]",
            "B2_7[7:0]",
            "B2_7[7:0]",
            "B2_7[7:0]",
            "B2_7[7:0]",
        ],
        "por state": "",
    },
    0xA9: {
        "address": 0xA9,
        "name": "EQUALIZER BAND 7 COEFFICIENT A1",
        "R/W": "R/W",
        "expanded_bitfields": [
            "A1_7[23:16]",
            "A1_7[23:16]",
            "A1_7[23:16]",
            "A1_7[23:16]",
            "A1_7[23:16]",
            "A1_7[23:16]",
            "A1_7[23:16]",
            "A1_7[23:16]",
        ],
        "por state": "",
    },
    0xAA: {
        "address": 0xAA,
        "name": "EQUALIZER BAND 7 COEFFICIENT A1",
        "R/W": "R/W",
        "expanded_bitfields": [
            "A1_7[15:8]",
            "A1_7[15:8]",
            "A1_7[15:8]",
            "A1_7[15:8]",
            "A1_7[15:8]",
            "A1_7[15:8]",
            "A1_7[15:8]",
            "A1_7[15:8]",
        ],
        "por state": "",
    },
    0xAB: {
        "address": 0xAB,
        "name": "EQUALIZER BAND 7 COEFFICIENT A1",
        "R/W": "R/W",
        "expanded_bitfields": [
            "A1_7[7:0]",
            "A1_7[7:0]",
            "A1_7[7:0]",
            "A1_7[7:0]",
            "A1_7[7:0]",
            "A1_7[7:0]",
            "A1_7[7:0]",
            "A1_7[7:0]",
        ],
        "por state": "",
    },
    0xAC: {
        "address": 0xAC,
        "name": "EQUALIZER BAND 7 COEFFICIENT A2",
        "R/W": "R/W",
        "expanded_bitfields": [
            "A2_7[23:16]",
            "A2_7[23:16]",
            "A2_7[23:16]",
            "A2_7[23:16]",
            "A2_7[23:16]",
            "A2_7[23:16]",
            "A2_7[23:16]",
            "A2_7[23:16]",
        ],
        "por state": "",
    },
    0xAD: {
        "address": 0xAD,
        "name": "EQUALIZER BAND 7 COEFFICIENT A2",
        "R/W": "R/W",
        "expanded_bitfields": [
            "A2_7[15:8]",
            "A2_7[15:8]",
            "A2_7[15:8]",
            "A2_7[15:8]",
            "A2_7[15:8]",
            "A2_7[15:8]",
            "A2_7[15:8]",
            "A2_7[15:8]",
        ],
        "por state": "",
    },
    0xAE: {
        "address": 0xAE,
        "name": "EQUALIZER BAND 7 COEFFICIENT A2",
        "R/W": "R/W",
        "expanded_bitfields": [
            "A2_7[7:0]",
            "A2_7[7:0]",
            "A2_7[7:0]",
            "A2_7[7:0]",
            "A2_7[7:0]",
            "A2_7[7:0]",
            "A2_7[7:0]",
            "A2_7[7:0]",
        ],
        "por state": "",
    },
    0xAF: {
        "address": 0xAF,
        "name": "RECORD BIQUAD COEFFICIENT B0",
        "R/W": "R/W",
        "expanded_bitfields": [
            "REC_B0[23:16]",
            "REC_B0[23:16]",
            "REC_B0[23:16]",
            "REC_B0[23:16]",
            "REC_B0[23:16]",
            "REC_B0[23:16]",
            "REC_B0[23:16]",
            "REC_B0[23:16]",
        ],
        "por state": "",
    },
    0xB0: {
        "address": 0xB0,
        "name": "RECORD BIQUAD COEFFICIENT B0",
        "R/W": "R/W",
        "expanded_bitfields": [
            "REC_B0[15:8]",
            "REC_B0[15:8]",
            "REC_B0[15:8]",
            "REC_B0[15:8]",
            "REC_B0[15:8]",
            "REC_B0[15:8]",
            "REC_B0[15:8]",
            "REC_B0[15:8]",
        ],
        "por state": "",
    },
    0xB1: {
        "address": 0xB1,
        "name": "RECORD BIQUAD COEFFICIENT B0",
        "R/W": "R/W",
        "expanded_bitfields": [
            "REC_B0[7:0]",
            "REC_B0[7:0]",
            "REC_B0[7:0]",
            "REC_B0[7:0]",
            "REC_B0[7:0]",
            "REC_B0[7:0]",
            "REC_B0[7:0]",
            "REC_B0[7:0]",
        ],
        "por state": "",
    },
    0xB2: {
        "address": 0xB2,
        "name": "RECORD BIQUAD COEFFICIENT B1",
        "R/W": "R/W",
        "expanded_bitfields": [
            "REC_B1[23:16]",
            "REC_B1[23:16]",
            "REC_B1[23:16]",
            "REC_B1[23:16]",
            "REC_B1[23:16]",
            "REC_B1[23:16]",
            "REC_B1[23:16]",
            "REC_B1[23:16]",
        ],
        "por state": "",
    },
    0xB3: {
        "address": 0xB3,
        "name": "RECORD BIQUAD COEFFICIENT B1",
        "R/W": "R/W",
        "expanded_bitfields": [
            "REC_B1[15:8]",
            "REC_B1[15:8]",
            "REC_B1[15:8]",
            "REC_B1[15:8]",
            "REC_B1[15:8]",
            "REC_B1[15:8]",
            "REC_B1[15:8]",
            "REC_B1[15:8]",
        ],
        "por state": "",
    },
    0xB4: {
        "address": 0xB4,
        "name": "RECORD BIQUAD COEFFICIENT B1",
        "R/W": "R/W",
        "expanded_bitfields": [
            "REC_B1[7:0]",
            "REC_B1[7:0]",
            "REC_B1[7:0]",
            "REC_B1[7:0]",
            "REC_B1[7:0]",
            "REC_B1[7:0]",
            "REC_B1[7:0]",
            "REC_B1[7:0]",
        ],
        "por state": "",
    },
    0xB5: {
        "address": 0xB5,
        "name": "RECORD BIQUAD COEFFICIENT B2",
        "R/W": "R/W",
        "expanded_bitfields": [
            "REC_B2[23:16]",
            "REC_B2[23:16]",
            "REC_B2[23:16]",
            "REC_B2[23:16]",
            "REC_B2[23:16]",
            "REC_B2[23:16]",
            "REC_B2[23:16]",
            "REC_B2[23:16]",
        ],
        "por state": "",
    },
    0xB6: {
        "address": 0xB6,
        "name": "RECORD BIQUAD COEFFICIENT B2",
        "R/W": "R/W",
        "expanded_bitfields": [
            "REC_B2[15:8]",
            "REC_B2[15:8]",
            "REC_B2[15:8]",
            "REC_B2[15:8]",
            "REC_B2[15:8]",
            "REC_B2[15:8]",
            "REC_B2[15:8]",
            "REC_B2[15:8]",
        ],
        "por state": "",
    },
    0xB7: {
        "address": 0xB7,
        "name": "RECORD BIQUAD COEFFICIENT B2",
        "R/W": "R/W",
        "expanded_bitfields": [
            "REC_B2[7:0]",
            "REC_B2[7:0]",
            "REC_B2[7:0]",
            "REC_B2[7:0]",
            "REC_B2[7:0]",
            "REC_B2[7:0]",
            "REC_B2[7:0]",
            "REC_B2[7:0]",
        ],
        "por state": "",
    },
    0xB8: {
        "address": 0xB8,
        "name": "RECORD BIQUAD COEFFICIENT A1",
        "R/W": "R/W",
        "expanded_bitfields": [
            "REC_A1[23:16]",
            "REC_A1[23:16]",
            "REC_A1[23:16]",
            "REC_A1[23:16]",
            "REC_A1[23:16]",
            "REC_A1[23:16]",
            "REC_A1[23:16]",
            "REC_A1[23:16]",
        ],
        "por state": "",
    },
    0xB9: {
        "address": 0xB9,
        "name": "RECORD BIQUAD COEFFICIENT A1",
        "R/W": "R/W",
        "expanded_bitfields": [
            "REC_A1[15:8]",
            "REC_A1[15:8]",
            "REC_A1[15:8]",
            "REC_A1[15:8]",
            "REC_A1[15:8]",
            "REC_A1[15:8]",
            "REC_A1[15:8]",
            "REC_A1[15:8]",
        ],
        "por state": "",
    },
    0xBA: {
        "address": 0xBA,
        "name": "RECORD BIQUAD COEFFICIENT A1",
        "R/W": "R/W",
        "expanded_bitfields": [
            "REC_A1[7:0]",
            "REC_A1[7:0]",
            "REC_A1[7:0]",
            "REC_A1[7:0]",
            "REC_A1[7:0]",
            "REC_A1[7:0]",
            "REC_A1[7:0]",
            "REC_A1[7:0]",
        ],
        "por state": "",
    },
    0xBB: {
        "address": 0xBB,
        "name": "RECORD BIQUAD COEFFICIENT A2",
        "R/W": "R/W",
        "expanded_bitfields": [
            "REC_A2[23:16]",
            "REC_A2[23:16]",
            "REC_A2[23:16]",
            "REC_A2[23:16]",
            "REC_A2[23:16]",
            "REC_A2[23:16]",
            "REC_A2[23:16]",
            "REC_A2[23:16]",
        ],
        "por state": "",
    },
    0xBC: {
        "address": 0xBC,
        "name": "RECORD BIQUAD COEFFICIENT A2",
        "R/W": "R/W",
        "expanded_bitfields": [
            "REC_A2[15:8]",
            "REC_A2[15:8]",
            "REC_A2[15:8]",
            "REC_A2[15:8]",
            "REC_A2[15:8]",
            "REC_A2[15:8]",
            "REC_A2[15:8]",
            "REC_A2[15:8]",
        ],
        "por state": "",
    },
    0xBD: {
        "address": 0xBD,
        "name": "RECORD BIQUAD COEFFICIENT A2",
        "R/W": "R/W",
        "expanded_bitfields": [
            "REC_A2[7:0]",
            "REC_A2[7:0]",
            "REC_A2[7:0]",
            "REC_A2[7:0]",
            "REC_A2[7:0]",
            "REC_A2[7:0]",
            "REC_A2[7:0]",
            "REC_A2[7:0]",
        ],
        "por state": "",
    },
    0xBE: {
        "address": 0xBE,
        "name": "DMIC2L RECORD LEVEL",
        "R/W": "R/W",
        "expanded_bitfields": [
            "",
            "AV2LG[2:0]",
            "AV2LG[2:0]",
            "AV2LG[2:0]",
            "AV2L[3:0]",
            "AV2L[3:0]",
            "AV2L[3:0]",
            "AV2L[3:0]",
        ],
        "por state": 0x03,
    },
    0xBF: {
        "address": 0xBF,
        "name": "DMIC2R RECORD LEVEL",
        "R/W": "R/W",
        "expanded_bitfields": [
            "",
            "AV2RG[2:0]",
            "AV2RG[2:0]",
            "AV2RG[2:0]",
            "AV2R[3:0]",
            "AV2R[3:0]",
            "AV2R[3:0]",
            "AV2R[3:0]",
        ],
        "por state": 0x03,
    },
    0xC0: {
        "address": 0xC0,
        "name": "DMIC2 BIQUAD LEVEL",
        "R/W": "R/W",
        "expanded_bitfields": [
            "",
            "",
            "",
            "",
            "AV2BQ[3:0]",
            "AV2BQ[3:0]",
            "AV2BQ[3:0]",
            "AV2BQ[3:0]",
        ],
        "por state": 0x00,
    },
    0xC1: {
        "address": 0xC1,
        "name": "RECORD TDM SLOT",
        "R/W": "R/W",
        "expanded_bitfields": [
            "SLOT_REC1L[1:0]",
            "SLOT_REC1L[1:0]",
            "SLOT_REC1R[1:0]",
            "SLOT_REC1R[1:0]",
            "SLOT_REC2L[1:0]",
            "SLOT_REC2L[1:0]",
            "SLOT_REC2R[1:0]",
            "SLOT_REC2R[1:0]",
        ],
        "por state": 0x1B,
    },
    0xC2: {
        "address": 0xC2,
        "name": "DMIC2 SAMPLE RATE",
        "R/W": "R/W",
        "expanded_bitfields": [
            "",
            "",
            "",
            "ZEROPAD",
            "",
            "SRDIV[2:0]",
            "SRDIV[2:0]",
            "SRDIV[2:0]",
        ],
        "por state": 0x10,
    },
    0xC3: {
        "address": 0xC3,
        "name": "DMIC34 BIQUAD COEFFICIENT B0",
        "R/W": "R/W",
        "expanded_bitfields": [
            "DMIC2_B0[23:16]",
            "DMIC2_B0[23:16]",
            "DMIC2_B0[23:16]",
            "DMIC2_B0[23:16]",
            "DMIC2_B0[23:16]",
            "DMIC2_B0[23:16]",
            "DMIC2_B0[23:16]",
            "DMIC2_B0[23:16]",
        ],
        "por state": "",
    },
    0xC4: {
        "address": 0xC4,
        "name": "DMIC34 BIQUAD COEFFICIENT B0",
        "R/W": "R/W",
        "expanded_bitfields": [
            "DMIC2_B0[15:8]",
            "DMIC2_B0[15:8]",
            "DMIC2_B0[15:8]",
            "DMIC2_B0[15:8]",
            "DMIC2_B0[15:8]",
            "DMIC2_B0[15:8]",
            "DMIC2_B0[15:8]",
            "DMIC2_B0[15:8]",
        ],
        "por state": "",
    },
    0xC5: {
        "address": 0xC5,
        "name": "DMIC34 BIQUAD COEFFICIENT B0",
        "R/W": "R/W",
        "expanded_bitfields": [
            "DMIC2_B0[7:0]",
            "DMIC2_B0[7:0]",
            "DMIC2_B0[7:0]",
            "DMIC2_B0[7:0]",
            "DMIC2_B0[7:0]",
            "DMIC2_B0[7:0]",
            "DMIC2_B0[7:0]",
            "DMIC2_B0[7:0]",
        ],
        "por state": "",
    },
    0xC6: {
        "address": 0xC6,
        "name": "DMIC34 BIQUAD COEFFICIENT B1",
        "R/W": "R/W",
        "expanded_bitfields": [
            "DMIC2_B1[23:16]",
            "DMIC2_B1[23:16]",
            "DMIC2_B1[23:16]",
            "DMIC2_B1[23:16]",
            "DMIC2_B1[23:16]",
            "DMIC2_B1[23:16]",
            "DMIC2_B1[23:16]",
            "DMIC2_B1[23:16]",
        ],
        "por state": "",
    },
    0xC7: {
        "address": 0xC7,
        "name": "DMIC34 BIQUAD COEFFICIENT B1",
        "R/W": "R/W",
        "expanded_bitfields": [
            "DMIC2_B1[15:8]",
            "DMIC2_B1[15:8]",
            "DMIC2_B1[15:8]",
            "DMIC2_B1[15:8]",
            "DMIC2_B1[15:8]",
            "DMIC2_B1[15:8]",
            "DMIC2_B1[15:8]",
            "DMIC2_B1[15:8]",
        ],
        "por state": "",
    },
    0xC8: {
        "address": 0xC8,
        "name": "DMIC34 BIQUAD COEFFICIENT B1",
        "R/W": "R/W",
        "expanded_bitfields": [
            "DMIC2_B1[7:0]",
            "DMIC2_B1[7:0]",
            "DMIC2_B1[7:0]",
            "DMIC2_B1[7:0]",
            "DMIC2_B1[7:0]",
            "DMIC2_B1[7:0]",
            "DMIC2_B1[7:0]",
            "DMIC2_B1[7:0]",
        ],
        "por state": "",
    },
    0xC9: {
        "address": 0xC9,
        "name": "DMIC34 BIQUAD COEFFICIENT B2",
        "R/W": "R/W",
        "expanded_bitfields": [
            "DMIC2_B2[23:16]",
            "DMIC2_B2[23:16]",
            "DMIC2_B2[23:16]",
            "DMIC2_B2[23:16]",
            "DMIC2_B2[23:16]",
            "DMIC2_B2[23:16]",
            "DMIC2_B2[23:16]",
            "DMIC2_B2[23:16]",
        ],
        "por state": "",
    },
    0xCA: {
        "address": 0xCA,
        "name": "DMIC34 BIQUAD COEFFICIENT B2",
        "R/W": "R/W",
        "expanded_bitfields": [
            "DMIC2_B2[15:8]",
            "DMIC2_B2[15:8]",
            "DMIC2_B2[15:8]",
            "DMIC2_B2[15:8]",
            "DMIC2_B2[15:8]",
            "DMIC2_B2[15:8]",
            "DMIC2_B2[15:8]",
            "DMIC2_B2[15:8]",
        ],
        "por state": "",
    },
    0xCB: {
        "address": 0xCB,
        "name": "DMIC34 BIQUAD COEFFICIENT B2",
        "R/W": "R/W",
        "expanded_bitfields": [
            "DMIC2_B2[7:0]",
            "DMIC2_B2[7:0]",
            "DMIC2_B2[7:0]",
            "DMIC2_B2[7:0]",
            "DMIC2_B2[7:0]",
            "DMIC2_B2[7:0]",
            "DMIC2_B2[7:0]",
            "DMIC2_B2[7:0]",
        ],
        "por state": "",
    },
    0xCC: {
        "address": 0xCC,
        "name": "DMIC34 BIQUAD COEFFICIENT A1",
        "R/W": "R/W",
        "expanded_bitfields": [
            "DMIC2_A1[23:16]",
            "DMIC2_A1[23:16]",
            "DMIC2_A1[23:16]",
            "DMIC2_A1[23:16]",
            "DMIC2_A1[23:16]",
            "DMIC2_A1[23:16]",
            "DMIC2_A1[23:16]",
            "DMIC2_A1[23:16]",
        ],
        "por state": "",
    },
    0xCD: {
        "address": 0xCD,
        "name": "DMIC34 BIQUAD COEFFICIENT A1",
        "R/W": "R/W",
        "expanded_bitfields": [
            "DMIC2_A1[15:8]",
            "DMIC2_A1[15:8]",
            "DMIC2_A1[15:8]",
            "DMIC2_A1[15:8]",
            "DMIC2_A1[15:8]",
            "DMIC2_A1[15:8]",
            "DMIC2_A1[15:8]",
            "DMIC2_A1[15:8]",
        ],
        "por state": "",
    },
    0xCE: {
        "address": 0xCE,
        "name": "DMIC34 BIQUAD COEFFICIENT A1",
        "R/W": "R/W",
        "expanded_bitfields": [
            "DMIC2_A1[7:0]",
            "DMIC2_A1[7:0]",
            "DMIC2_A1[7:0]",
            "DMIC2_A1[7:0]",
            "DMIC2_A1[7:0]",
            "DMIC2_A1[7:0]",
            "DMIC2_A1[7:0]",
            "DMIC2_A1[7:0]",
        ],
        "por state": "",
    },
    0xCF: {
        "address": 0xCF,
        "name": "DMIC34 BIQUAD COEFFICIENT A2",
        "R/W": "R/W",
        "expanded_bitfields": [
            "DMIC2_A2[23:16]",
            "DMIC2_A2[23:16]",
            "DMIC2_A2[23:16]",
            "DMIC2_A2[23:16]",
            "DMIC2_A2[23:16]",
            "DMIC2_A2[23:16]",
            "DMIC2_A2[23:16]",
            "DMIC2_A2[23:16]",
        ],
        "por state": "",
    },
    0xD0: {
        "address": 0xD0,
        "name": "DMIC34 BIQUAD COEFFICIENT A2",
        "R/W": "R/W",
        "expanded_bitfields": [
            "DMIC2_A2[15:8]",
            "DMIC2_A2[15:8]",
            "DMIC2_A2[15:8]",
            "DMIC2_A2[15:8]",
            "DMIC2_A2[15:8]",
            "DMIC2_A2[15:8]",
            "DMIC2_A2[15:8]",
            "DMIC2_A2[15:8]",
        ],
        "por state": "",
    },
    0xD1: {
        "address": 0xD1,
        "name": "DMIC34 BIQUAD COEFFICIENT A2",
        "R/W": "R/W",
        "expanded_bitfields": [
            "DMIC2_A2[7:0]",
            "DMIC2_A2[7:0]",
            "DMIC2_A2[7:0]",
            "DMIC2_A2[7:0]",
            "DMIC2_A2[7:0]",
            "DMIC2_A2[7:0]",
            "DMIC2_A2[7:0]",
            "DMIC2_A2[7:0]",
        ],
        "por state": "",
    },
    0xFF: {
        "address": 0xFF,
        "name": "REVISION ID",
        "R/W": "R",
        "expanded_bitfields": [
            "REVID[7:0]",
            "REVID[7:0]",
            "REVID[7:0]",
            "REVID[7:0]",
            "REVID[7:0]",
            "REVID[7:0]",
            "REVID[7:0]",
            "REVID[7:0]",
        ],
        "por state": "",
    },
}
