reference_map = {
    0: {

    8: {
        0: 'REFL[7:0]',
        1: 'REFL[7:0]',
        2: 'REFL[7:0]',
        3: 'REFL[7:0]',
        4: 'REFL[7:0]',
        5: 'REFL[7:0]',
        6: 'REFL[7:0]',
        7: 'REFL[7:0]',
        'address': 8,
        'last_read_value': None,
        'name': 'REF_P_XL'},
    9: {
        0: 'REFL[15:8]',
        1: 'REFL[15:8]',
        2: 'REFL[15:8]',
        3: 'REFL[15:8]',
        4: 'REFL[15:8]',
        5: 'REFL[15:8]',
        6: 'REFL[15:8]',
        7: 'REFL[15:8]',
        'address': 9,
        'last_read_value': None,
        'name': 'REF_P_L'},
    10: {
        0: 'REFL[23:16]',
        1: 'REFL[23:16]',
        2: 'REFL[23:16]',
        3: 'REFL[23:16]',
        4: 'REFL[23:16]',
        5: 'REFL[23:16]',
        6: 'REFL[23:16]',
        7: 'REFL[23:16]',
        'address': 10,
        'last_read_value': None,
        'name': 'REF_P_H'},
    16: {
        0: 'AVGP0',
        1: 'AVGP1',
        2: 'AVGT0',
        3: 'AVGT1',
        4: '',
        5: '',
        6: '',
        7: '',
        'address': 16,
        'last_read_value': None,
        'name': 'RES_CONF'},
    96: {
        0: 'AGAIN_STATUS [3:0]',
        1: 'AGAIN_STATUS [3:0]',
        2: 'AGAIN_STATUS [3:0]',
        3: 'AGAIN_STATUS [3:0]',
        4: '',
        5: '',
        6: '',
        7: 'ASAT_STATUS',
        'address': 96,
        'last_read_value': None,
        'name': 'ASTATUS'},
    97: {
        0: 'CH0_DATA_L [7:0]',
        1: 'CH0_DATA_L [7:0]',
        2: 'CH0_DATA_L [7:0]',
        3: 'CH0_DATA_L [7:0]',
        4: 'CH0_DATA_L [7:0]',
        5: 'CH0_DATA_L [7:0]',
        6: 'CH0_DATA_L [7:0]',
        7: 'CH0_DATA_L [7:0]',
        'address': 97,
        'last_read_value': None,
        'name': 'CH0_DATA_L '},
    98: {
        0: 'CH0_DATA_H [7:0]',
        1: 'CH0_DATA_H [7:0]',
        2: 'CH0_DATA_H [7:0]',
        3: 'CH0_DATA_H [7:0]',
        4: 'CH0_DATA_H [7:0]',
        5: 'CH0_DATA_H [7:0]',
        6: 'CH0_DATA_H [7:0]',
        7: 'CH0_DATA_H [7:0]',
        'address': 98,
        'last_read_value': None,
        'name': 'CH0_DATA_H'},
    99: {
        0: 'ITIME_L [7:0]',
        1: 'ITIME_L [7:0]',
        2: 'ITIME_L [7:0]',
        3: 'ITIME_L [7:0]',
        4: 'ITIME_L [7:0]',
        5: 'ITIME_L [7:0]',
        6: 'ITIME_L [7:0]',
        7: 'ITIME_L [7:0]',
        'address': 99,
        'last_read_value': None,
        'name': 'ITIME_L'},
    100: {
        0: 'ITIME_M [7:0]',
        1: 'ITIME_M [7:0]',
        2: 'ITIME_M [7:0]',
        3: 'ITIME_M [7:0]',
        4: 'ITIME_M [7:0]',
        5: 'ITIME_M [7:0]',
        6: 'ITIME_M [7:0]',
        7: 'ITIME_M [7:0]',
        'address': 100,
        'last_read_value': None,
        'name': 'ITIME_M'},
    101: {
        0: 'ITIME_H [7:0]',
        1: 'ITIME_H [7:0]',
        2: 'ITIME_H [7:0]',
        3: 'ITIME_H [7:0]',
        4: 'ITIME_H [7:0]',
        5: 'ITIME_H [7:0]',
        6: 'ITIME_H [7:0]',
        7: 'ITIME_H [7:0]',
        'address': 101,
        'last_read_value': None,
        'name': 'ITIME_H'},
    102: {
        0: 'CH1_DATA_L [7:0]',
        1: 'CH1_DATA_L [7:0]',
        2: 'CH1_DATA_L [7:0]',
        3: 'CH1_DATA_L [7:0]',
        4: 'CH1_DATA_L [7:0]',
        5: 'CH1_DATA_L [7:0]',
        6: 'CH1_DATA_L [7:0]',
        7: 'CH1_DATA_L [7:0]',
        'address': 102,
        'last_read_value': None,
        'name': 'CH1_DATA_L'},
    103: {
        0: 'CH1_DATA_H [7:0]',
        1: 'CH1_DATA_H [7:0]',
        2: 'CH1_DATA_H [7:0]',
        3: 'CH1_DATA_H [7:0]',
        4: 'CH1_DATA_H [7:0]',
        5: 'CH1_DATA_H [7:0]',
        6: 'CH1_DATA_H [7:0]',
        7: 'CH1_DATA_H [7:0]',
        'address': 103,
        'last_read_value': None,
        'name': 'CH1_DATA_H'},
    104: {
        0: 'CH2_DATA_L [7:0]',
        1: 'CH2_DATA_L [7:0]',
        2: 'CH2_DATA_L [7:0]',
        3: 'CH2_DATA_L [7:0]',
        4: 'CH2_DATA_L [7:0]',
        5: 'CH2_DATA_L [7:0]',
        6: 'CH2_DATA_L [7:0]',
        7: 'CH2_DATA_L [7:0]',
        'address': 104,
        'last_read_value': None,
        'name': 'CH2_DATA_L'},
    105: {
        0: 'CH2_DATA_H [7:0]',
        1: 'CH2_DATA_H [7:0]',
        2: 'CH2_DATA_H [7:0]',
        3: 'CH2_DATA_H [7:0]',
        4: 'CH2_DATA_H [7:0]',
        5: 'CH2_DATA_H [7:0]',
        6: 'CH2_DATA_H [7:0]',
        7: 'CH2_DATA_H [7:0]',
        'address': 105,
        'last_read_value': None,
        'name': 'CH2_DATA_H'},
    106: {
        0: 'CH3_DATA_L [7:0]',
        1: 'CH3_DATA_L [7:0]',
        2: 'CH3_DATA_L [7:0]',
        3: 'CH3_DATA_L [7:0]',
        4: 'CH3_DATA_L [7:0]',
        5: 'CH3_DATA_L [7:0]',
        6: 'CH3_DATA_L [7:0]',
        7: 'CH3_DATA_L [7:0]',
        'address': 106,
        'last_read_value': None,
        'name': 'CH3_DATA_L'},
    107: {
        0: 'CH3_DATA_H [7:0]',
        1: 'CH3_DATA_H [7:0]',
        2: 'CH3_DATA_H [7:0]',
        3: 'CH3_DATA_H [7:0]',
        4: 'CH3_DATA_H [7:0]',
        5: 'CH3_DATA_H [7:0]',
        6: 'CH3_DATA_H [7:0]',
        7: 'CH3_DATA_H [7:0]',
        'address': 107,
        'last_read_value': None,
        'name': 'CH3_DATA_H'},
    108: {
        0: 'CH4_DATA_L [7:0]',
        1: 'CH4_DATA_L [7:0]',
        2: 'CH4_DATA_L [7:0]',
        3: 'CH4_DATA_L [7:0]',
        4: 'CH4_DATA_L [7:0]',
        5: 'CH4_DATA_L [7:0]',
        6: 'CH4_DATA_L [7:0]',
        7: 'CH4_DATA_L [7:0]',
        'address': 108,
        'last_read_value': None,
        'name': 'CH4_DATA_L'},
    109: {
        0: 'CH4_DATA_H [7:0]',
        1: 'CH4_DATA_H [7:0]',
        2: 'CH4_DATA_H [7:0]',
        3: 'CH4_DATA_H [7:0]',
        4: 'CH4_DATA_H [7:0]',
        5: 'CH4_DATA_H [7:0]',
        6: 'CH4_DATA_H [7:0]',
        7: 'CH4_DATA_H [7:0]',
        'address': 109,
        'last_read_value': None,
        'name': 'CH4_DATA_H'},
    110: {
        0: 'CH5_DATA_L [7:0]',
        1: 'CH5_DATA_L [7:0]',
        2: 'CH5_DATA_L [7:0]',
        3: 'CH5_DATA_L [7:0]',
        4: 'CH5_DATA_L [7:0]',
        5: 'CH5_DATA_L [7:0]',
        6: 'CH5_DATA_L [7:0]',
        7: 'CH5_DATA_L [7:0]',
        'address': 110,
        'last_read_value': None,
        'name': 'CH5_DATA_L'},
    111: {
        0: 'CH5_DATA_H [7:0]',
        1: 'CH5_DATA_H [7:0]',
        2: 'CH5_DATA_H [7:0]',
        3: 'CH5_DATA_H [7:0]',
        4: 'CH5_DATA_H [7:0]',
        5: 'CH5_DATA_H [7:0]',
        6: 'CH5_DATA_H [7:0]',
        7: 'CH5_DATA_H [7:0]',
        'address': 111,
        'last_read_value': None,
        'name': 'CH5_DATA_H'},
    112: {
        0: 'INT_MODE[1:0]',
        1: 'INT_MODE[1:0]',
        2: 'INT_SEL',
        3: 'LED_SEL',
        4: '',
        5: '',
        6: '',
        7: '',
        'address': 112,
        'last_read_value': None,
        'name': 'CONFIG'},
    113: {
        0: 'READY',
        1: 'WAIT_SYNC',
        2: '',
        3: '',
        4: '',
        5: '',
        6: '',
        7: '',
        'address': 113,
        'last_read_value': None,
        'name': 'STAT'},
    114: {
        0: 'SYNC_EDGE [7:0]',
        1: 'SYNC_EDGE [7:0]',
        2: 'SYNC_EDGE [7:0]',
        3: 'SYNC_EDGE [7:0]',
        4: 'SYNC_EDGE [7:0]',
        5: 'SYNC_EDGE [7:0]',
        6: 'SYNC_EDGE [7:0]',
        7: 'SYNC_EDGE [7:0]',
        'address': 114,
        'last_read_value': None,
        'name': 'EDGE'},
    115: {
        0: 'PD_INT',
        1: 'PD_GPIO',
        2: '',
        3: '',
        4: '',
        5: '',
        6: '',
        7: '',
        'address': 115,
        'last_read_value': None,
        'name': 'GPIO'},
    116: {
        0: 'LED_DRIVE [6:0]',
        1: 'LED_DRIVE [6:0]',
        2: 'LED_DRIVE [6:0]',
        3: 'LED_DRIVE [6:0]',
        4: 'LED_DRIVE [6:0]',
        5: 'LED_DRIVE [6:0]',
        6: 'LED_DRIVE [6:0]',
        7: 'LED_ACT',
        'address': 116,
        'last_read_value': None,
        'name': 'LED'},
    128: {
        0: 'PON',
        1: 'SP_EN',
        2: '',
        3: ' WEN',
        4: 'SMUXEN',
        5: '',
        6: '',
        7: 'FDEN',
        'address': 128,
        'last_read_value': None,
        'name': 'ENABLE'},
    129: {
        0: 'ATIME [7:0]',
        1: 'ATIME [7:0]',
        2: 'ATIME [7:0]',
        3: 'ATIME [7:0]',
        4: 'ATIME [7:0]',
        5: 'ATIME [7:0]',
        6: 'ATIME [7:0]',
        7: 'ATIME [7:0]',
        'address': 129,
        'last_read_value': None,
        'name': 'ATIME'},
    131: {
        0: 'WTIME [7:0]',
        1: 'WTIME [7:0]',
        2: 'WTIME [7:0]',
        3: 'WTIME [7:0]',
        4: 'WTIME [7:0]',
        5: 'WTIME [7:0]',
        6: 'WTIME [7:0]',
        7: 'WTIME [7:0]',
        'address': 131,
        'last_read_value': None,
        'name': 'WTIME'},
    132: {
        0: 'SP_TH_L_LSB [7:0]',
        1: 'SP_TH_L_LSB [7:0]',
        2: 'SP_TH_L_LSB [7:0]',
        3: 'SP_TH_L_LSB [7:0]',
        4: 'SP_TH_L_LSB [7:0]',
        5: 'SP_TH_L_LSB [7:0]',
        6: 'SP_TH_L_LSB [7:0]',
        7: 'SP_TH_L_LSB [7:0]',
        'address': 132,
        'last_read_value': None,
        'name': 'SP_LOW_TH_L'},
    133: {
        0: 'SP_TH_L_MSB [7:0]',
        1: 'SP_TH_L_MSB [7:0]',
        2: 'SP_TH_L_MSB [7:0]',
        3: 'SP_TH_L_MSB [7:0]',
        4: 'SP_TH_L_MSB [7:0]',
        5: 'SP_TH_L_MSB [7:0]',
        6: 'SP_TH_L_MSB [7:0]',
        7: 'SP_TH_L_MSB [7:0]',
        'address': 133,
        'last_read_value': None,
        'name': 'SP_LOW_TH_H'},
    134: {
        0: 'SP_TH_H_LSB [7:0]',
        1: 'SP_TH_H_LSB [7:0]',
        2: 'SP_TH_H_LSB [7:0]',
        3: 'SP_TH_H_LSB [7:0]',
        4: 'SP_TH_H_LSB [7:0]',
        5: 'SP_TH_H_LSB [7:0]',
        6: 'SP_TH_H_LSB [7:0]',
        7: 'SP_TH_H_LSB [7:0]',
        'address': 134,
        'last_read_value': None,
        'name': 'SP_HIGH_TH_L'},
    135: {
        0: 'SP_TH_H_MSB [7:0]',
        1: 'SP_TH_H_MSB [7:0]',
        2: 'SP_TH_H_MSB [7:0]',
        3: 'SP_TH_H_MSB [7:0]',
        4: 'SP_TH_H_MSB [7:0]',
        5: 'SP_TH_H_MSB [7:0]',
        6: 'SP_TH_H_MSB [7:0]',
        7: 'SP_TH_H_MSB [7:0]',
        'address': 135,
        'last_read_value': None,
        'name': 'SP_HIGH_TH_H'},
    144: {
        0: 'AUXID [7:0]',
        1: 'AUXID [7:0]',
        2: 'AUXID [7:0]',
        3: 'AUXID [7:0]',
        4: 'AUXID [7:0]',
        5: 'AUXID [7:0]',
        6: 'AUXID [7:0]',
        7: 'AUXID [7:0]',
        'address': 144,
        'last_read_value': None,
        'name': 'AUXID'},
    145: {
        0: 'REVID [7:0]',
        1: 'REVID [7:0]',
        2: 'REVID [7:0]',
        3: 'REVID [7:0]',
        4: 'REVID [7:0]',
        5: 'REVID [7:0]',
        6: 'REVID [7:0]',
        7: 'REVID [7:0]',
        'address': 145,
        'last_read_value': None,
        'name': 'REVID'},
    146: {
        0: 'ID [7:0]',
        1: 'ID [7:0]',
        2: 'ID [7:0]',
        3: 'ID [7:0]',
        4: 'ID [7:0]',
        5: 'ID [7:0]',
        6: 'ID [7:0]',
        7: 'ID [7:0]',
        'address': 146,
        'last_read_value': None,
        'name': 'ID'},
    147: {
        0: 'SINT',
        1: 'CINT',
        2: 'FINT',
        3: '',
        4: 'AINT',
        5: '',
        6: '',
        7: 'ASAT',
        'address': 147,
        'last_read_value': None,
        'name': 'STATUS'},
    148: {
        0: 'AGAIN_STATUS [3:0]',
        1: 'AGAIN_STATUS [3:0]',
        2: 'AGAIN_STATUS [3:0]',
        3: 'AGAIN_STATUS [3:0]',
        4: '',
        5: '',
        6: '',
        7: 'ASAT_STATUS',
        'address': 148,
        'last_read_value': None,
        'name': 'ASTATUS'},
    149: {
        0: 'CH0_DATA_L [7:0]',
        1: 'CH0_DATA_L [7:0]',
        2: 'CH0_DATA_L [7:0]',
        3: 'CH0_DATA_L [7:0]',
        4: 'CH0_DATA_L [7:0]',
        5: 'CH0_DATA_L [7:0]',
        6: 'CH0_DATA_L [7:0]',
        7: 'CH0_DATA_L [7:0]',
        'address': 149,
        'last_read_value': None,
        'name': 'CH0_DATA_L'},
    150: {
        0: 'CH0_DATA_H [7:0]',
        1: 'CH0_DATA_H [7:0]',
        2: 'CH0_DATA_H [7:0]',
        3: 'CH0_DATA_H [7:0]',
        4: 'CH0_DATA_H [7:0]',
        5: 'CH0_DATA_H [7:0]',
        6: 'CH0_DATA_H [7:0]',
        7: 'CH0_DATA_H [7:0]',
        'address': 150,
        'last_read_value': None,
        'name': 'CH0_DATA_H'},
    151: {
        0: 'CH1_DATA_L [7:0]',
        1: 'CH1_DATA_L [7:0]',
        2: 'CH1_DATA_L [7:0]',
        3: 'CH1_DATA_L [7:0]',
        4: 'CH1_DATA_L [7:0]',
        5: 'CH1_DATA_L [7:0]',
        6: 'CH1_DATA_L [7:0]',
        7: 'CH1_DATA_L [7:0]',
        'address': 151,
        'last_read_value': None,
        'name': 'CH1_DATA_L'},
    152: {
        0: 'CH1_DATA_H [7:0]',
        1: 'CH1_DATA_H [7:0]',
        2: 'CH1_DATA_H [7:0]',
        3: 'CH1_DATA_H [7:0]',
        4: 'CH1_DATA_H [7:0]',
        5: 'CH1_DATA_H [7:0]',
        6: 'CH1_DATA_H [7:0]',
        7: 'CH1_DATA_H [7:0]',
        'address': 152,
        'last_read_value': None,
        'name': 'CH1_DATA_H'},
    153: {
        0: 'CH2_DATA_L [7:0]',
        1: 'CH2_DATA_L [7:0]',
        2: 'CH2_DATA_L [7:0]',
        3: 'CH2_DATA_L [7:0]',
        4: 'CH2_DATA_L [7:0]',
        5: 'CH2_DATA_L [7:0]',
        6: 'CH2_DATA_L [7:0]',
        7: 'CH2_DATA_L [7:0]',
        'address': 153,
        'last_read_value': None,
        'name': 'CH2_DATA_L'},
    154: {
        0: 'CH2_DATA_H [7:0]',
        1: 'CH2_DATA_H [7:0]',
        2: 'CH2_DATA_H [7:0]',
        3: 'CH2_DATA_H [7:0]',
        4: 'CH2_DATA_H [7:0]',
        5: 'CH2_DATA_H [7:0]',
        6: 'CH2_DATA_H [7:0]',
        7: 'CH2_DATA_H [7:0]',
        'address': 154,
        'last_read_value': None,
        'name': 'CH2_DATA_H'},
    155: {
        0: 'CH3_DATA_L [7:0]',
        1: 'CH3_DATA_L [7:0]',
        2: 'CH3_DATA_L [7:0]',
        3: 'CH3_DATA_L [7:0]',
        4: 'CH3_DATA_L [7:0]',
        5: 'CH3_DATA_L [7:0]',
        6: 'CH3_DATA_L [7:0]',
        7: 'CH3_DATA_L [7:0]',
        'address': 155,
        'last_read_value': None,
        'name': 'CH3_DATA_L'},
    156: {
        0: 'CH3_DATA_H [7:0]',
        1: 'CH3_DATA_H [7:0]',
        2: 'CH3_DATA_H [7:0]',
        3: 'CH3_DATA_H [7:0]',
        4: 'CH3_DATA_H [7:0]',
        5: 'CH3_DATA_H [7:0]',
        6: 'CH3_DATA_H [7:0]',
        7: 'CH3_DATA_H [7:0]',
        'address': 156,
        'last_read_value': None,
        'name': 'CH3_DATA_H'},
    157: {
        0: 'CH4_DATA_L [7:0]',
        1: 'CH4_DATA_L [7:0]',
        2: 'CH4_DATA_L [7:0]',
        3: 'CH4_DATA_L [7:0]',
        4: 'CH4_DATA_L [7:0]',
        5: 'CH4_DATA_L [7:0]',
        6: 'CH4_DATA_L [7:0]',
        7: 'CH4_DATA_L [7:0]',
        'address': 157,
        'last_read_value': None,
        'name': 'CH4_DATA_L'},
    158: {
        0: 'CH4_DATA_H [7:0]',
        1: 'CH4_DATA_H [7:0]',
        2: 'CH4_DATA_H [7:0]',
        3: 'CH4_DATA_H [7:0]',
        4: 'CH4_DATA_H [7:0]',
        5: 'CH4_DATA_H [7:0]',
        6: 'CH4_DATA_H [7:0]',
        7: 'CH4_DATA_H [7:0]',
        'address': 158,
        'last_read_value': None,
        'name': 'CH4_DATA_H'},
    159: {
        0: 'CH5_DATA_L [7:0]',
        1: 'CH5_DATA_L [7:0]',
        2: 'CH5_DATA_L [7:0]',
        3: 'CH5_DATA_L [7:0]',
        4: 'CH5_DATA_L [7:0]',
        5: 'CH5_DATA_L [7:0]',
        6: 'CH5_DATA_L [7:0]',
        7: 'CH5_DATA_L [7:0]',
        'address': 159,
        'last_read_value': None,
        'name': 'CH5_DATA_L'},
    160: {
        0: 'CH5_DATA_H [7:0]',
        1: 'CH5_DATA_H [7:0]',
        2: 'CH5_DATA_H [7:0]',
        3: 'CH5_DATA_H [7:0]',
        4: 'CH5_DATA_H [7:0]',
        5: 'CH5_DATA_H [7:0]',
        6: 'CH5_DATA_H [7:0]',
        7: 'CH5_DATA_H [7:0]',
        'address': 160,
        'last_read_value': None,
        'name': 'CH5_DATA_H'},
    163: {
        0: 'FDSAT_DIG',
        1: 'FDSAT_ANA',
        2: '',
        3: 'ASAT_ ANA',
        4: 'ASAT_DIG',
        5: '',
        6: 'AVALID',
        7: '',
        'address': 163,
        'last_read_value': None,
        'name': 'STATUS 2'},
    164: {
        0: '',
        1: '',
        2: '',
        3: '',
        4: 'INT_SP_L',
        5: 'INT_SP_H',
        6: '',
        7: '',
        'address': 164,
        'last_read_value': None,
        'name': 'STATUS 3'},
    166: {
        0: '',
        1: '',
        2: '',
        3: 'SINT_FD',
        4: '',
        5: '',
        6: '',
        7: '',
        'address': 166,
        'last_read_value': None,
        'name': 'STATUS 5'},
    167: {
        0: 'INT_BUSY',
        1: 'SAI_ACT',
        2: 'SP_TRIG',
        3: '',
        4: 'FD_TRIG',
        5: 'OVTEMP',
        6: '',
        7: 'FIFO_OV',
        'address': 167,
        'last_read_value': None,
        'name': 'STATUS 6'},
    169: {
        0: '',
        1: '',
        2: 'WLONG',
        3: 'REG_BANK',
        4: '',
        5: 'LOW_POWER',
        6: '',
        7: '',
        'address': 169,
        'last_read_value': None,
        'name': 'CFG 0'},
    170: {
        0: 'AGAIN[4:0]',
        1: 'AGAIN[4:0]',
        2: 'AGAIN[4:0]',
        3: 'AGAIN[4:0]',
        4: '',
        5: '',
        6: '',
        7: '',
        'address': 170,
        'last_read_value': None,
        'name': 'CFG 1'},
    172: {
        0: '',
        1: '',
        2: '',
        3: '',
        4: 'SAI',
        5: '',
        6: '',
        7: '',
        'address': 172,
        'last_read_value': None,
        'name': 'CFG 3'},
    175: {
        0: '',
        1: '',
        2: '',
        3: 'SMUX_CMD[4:3]',
        4: 'SMUX_CMD[4:3]',
        5: '',
        6: '',
        7: '',
        'address': 175,
        'last_read_value': None,
        'name': 'CFG 6'},
    177: {
        0: '',
        1: '',
        2: 'SP_AGC',
        3: 'FD_AGC',
        4: '',
        5: '',
        6: 'FIFO_TH [7:6]',
        7: 'FIFO_TH [7:6]',
        'address': 177,
        'last_read_value': None,
        'name': 'CFG 8'},
    178: {
        0: '',
        1: '',
        2: '',
        3: '',
        4: 'SIEN_SMUX',
        5: '',
        6: 'SIEN_FD',
        7: '',
        'address': 178,
        'last_read_value': None,
        'name': 'CFG 9'},
    179: {
        0: 'FD_PERS [2:0]',
        1: 'FD_PERS [2:0]',
        2: '',
        3: '',
        4: '',
        5: '',
        6: 'AGC_L[7:6]',
        7: 'AGC_H [7:6]',
        'address': 179,
        'last_read_value': None,
        'name': 'CFG 10'},
    181: {
        0: 'SP_TH_CH [2:0]',
        1: 'SP_TH_CH [2:0]',
        2: '',
        3: '',
        4: '',
        5: '',
        6: '',
        7: '',
        'address': 181,
        'last_read_value': None,
        'name': 'CFG 12'},
    189: {
        0: 'APERS [3:0]',
        1: 'APERS [3:0]',
        2: 'APERS [3:0]',
        3: 'APERS [3:0]',
        4: '',
        5: '',
        6: '',
        7: '',
        'address': 189,
        'last_read_value': None,
        'name': 'PERS'},
    190: {
        0: 'GPIO_IN',
        1: 'GPIO_OUT',
        2: 'GPIO_IN',
        3: 'GPIO_INV',
        4: '',
        5: '',
        6: '',
        7: '',
        'address': 190,
        'last_read_value': None,
        'name': 'GPIO 2'},
    202: {
        0: '',
        1: '',
        2: '',
        3: '',
        4: 'ASTEP [7:0]',
        5: '',
        6: '',
        7: '',
        'address': 202,
        'last_read_value': None,
        'name': 'ASTEP_L'},
    203: {
        0: '',
        1: '',
        2: '',
        3: '',
        4: 'ASTEP [15:8]',
        5: '',
        6: '',
        7: '',
        'address': 203,
        'last_read_value': None,
        'name': 'ASTEP_H'},
    207: {
        0: 'AGC_AGAIN_MAX [3:0]',
        1: 'AGC_AGAIN_MAX [3:0]',
        2: 'AGC_AGAIN_MAX [3:0]',
        3: 'AGC_AGAIN_MAX [3:0]',
        4: 'AGC_FD_GAIN_MAX [7:4]',
        5: 'AGC_FD_GAIN_MAX [7:4]',
        6: 'AGC_FD_GAIN_MAX [7:4]',
        7: 'AGC_FD_GAIN_MAX [7:4]',
        'address': 207,
        'last_read_value': None,
        'name': 'AGC_GAIN_MAX'},
    214: {
        0: '',
        1: '',
        2: '',
        3: '',
        4: 'AT_NTH_ITERATION [7:0]',
        5: '',
        6: '',
        7: '',
        'address': 214,
        'last_read_value': None,
        'name': 'AZ_CONFIG'},
    215: {
        0: '',
        1: '',
        2: '',
        3: '',
        4: '',
        5: 'FD_SAMPLES[6:5] *',
        6: 'FD_SAMPLES[6:5] *',
        7: 'FD_FIFO',
        'address': 215,
        'last_read_value': None,
        'name': 'FD_CFG0'},
    216: {
        0: '',
        1: '',
        2: '',
        3: '',
        4: 'FD_TIME [7:0]',
        5: '',
        6: '',
        7: '',
        'address': 216,
        'last_read_value': None,
        'name': 'FD_TIME 1'},
    218: {
        0: '',
        1: '',
        2: 'FD_TIME [10:8]',
        3: '',
        4: '',
        5: '',
        6: '',
        7: 'FD_GAIN [7:3]',
        'address': 218,
        'last_read_value': None,
        'name': 'FD_TIME 2'},
    219: {
        0: 'FD_100Hz',
        1: 'FD_120Hz',
        2: 'FD_100Hz_VALID',
        3: 'FD_120HZ_VALID',
        4: 'FD_SAT',
        5: 'FD_VALID',
        6: '',
        7: '',
        'address': 219,
        'last_read_value': None,
        'name': 'FD_STATUS'},
    249: {
        0: 'SIEN',
        1: 'CIEN',
        2: 'FIEN',
        3: '',
        4: 'SP_IEN',
        5: '',
        6: '',
        7: 'ASIEN',
        'address': 249,
        'last_read_value': None,
        'name': 'INTENAB'},
    250: {
        0: 'CLEAR_SAI_ACT',
        1: 'FIFO_CLR',
        2: 'AZ_SP_MAN',
        3: '',
        4: '',
        5: '',
        6: '',
        7: '',
        'address': 250,
        'last_read_value': None,
        'name': 'CONTROL'},
    252: {
        0: 'ASTATUS',
        1: 'FIFO_WRITE_CH5_DATA – FIFO_WRITE_CH0_DATA [6:1]',
        2: 'FIFO_WRITE_CH5_DATA – FIFO_WRITE_CH0_DATA [6:1]',
        3: 'FIFO_WRITE_CH5_DATA – FIFO_WRITE_CH0_DATA [6:1]',
        4: 'FIFO_WRITE_CH5_DATA – FIFO_WRITE_CH0_DATA [6:1]',
        5: 'FIFO_WRITE_CH5_DATA – FIFO_WRITE_CH0_DATA [6:1]',
        6: 'FIFO_WRITE_CH5_DATA – FIFO_WRITE_CH0_DATA [6:1]',
        7: 'FIFO_WRITE_CH5_DATA – FIFO_WRITE_CH0_DATA [6:1]',
        'address': 252,
        'last_read_value': None,
        'name': 'FIFO_MAP'},
    253: {
        0: 'FIFO_LVL [7:0]',
        1: 'FIFO_LVL [7:0]',
        2: 'FIFO_LVL [7:0]',
        3: 'FIFO_LVL [7:0]',
        4: 'FIFO_LVL [7:0]',
        5: 'FIFO_LVL [7:0]',
        6: 'FIFO_LVL [7:0]',
        7: 'FIFO_LVL [7:0]',
        'address': 253,
        'last_read_value': None,
        'name': 'FIFO_LVL'},
    254: {
        0: 'FDATA [7:0]',
        1: 'FDATA [7:0]',
        2: 'FDATA [7:0]',
        3: 'FDATA [7:0]',
        4: 'FDATA [7:0]',
        5: 'FDATA [7:0]',
        6: 'FDATA [7:0]',
        7: 'FDATA [7:0]',
        'address': 254,
        'last_read_value': None,
        'name': 'FDATA_L'},
    255: {
        0: 'FDATA [15:8]',
        1: 'FDATA [15:8]',
        2: 'FDATA [15:8]',
        3: 'FDATA [15:8]',
        4: 'FDATA [15:8]',
        5: 'FDATA [15:8]',
        6: 'FDATA [15:8]',
        7: 'FDATA [15:8]',
        'address': 255,
        'last_read_value': None,
           'name': 'FDATA_H'}}}