reference_map = {
    0: {

    8: {
        0: 'REFL[7:0]',
        1: 'REFL[7:0]',
        2: 'REFL[7:0]',
        3: 'REFL[7:0]',
        4: 'REFL[7:0]',
        5: 'REFL[7:0]',
        6: 'REFL[7:0]',
        7: 'REFL[7:0]',
        'address': 8,
        'last_read_value': None,
        'name': 'REF_P_XL'},
    9: {
        0: 'REFL[15:8]',
        1: 'REFL[15:8]',
        2: 'REFL[15:8]',
        3: 'REFL[15:8]',
        4: 'REFL[15:8]',
        5: 'REFL[15:8]',
        6: 'REFL[15:8]',
        7: 'REFL[15:8]',
        'address': 9,
        'last_read_value': None,
        'name': 'REF_P_L'},

    207: {
        0: 'AGC_AGAIN_MAX [3:0]',
        1: 'AGC_AGAIN_MAX [3:0]',
        2: 'AGC_AGAIN_MAX [3:0]',
        3: 'AGC_AGAIN_MAX [3:0]',
        4: 'AGC_FD_GAIN_MAX [7:4]',
        5: 'AGC_FD_GAIN_MAX [7:4]',
        6: 'AGC_FD_GAIN_MAX [7:4]',
        7: 'AGC_FD_GAIN_MAX [7:4]',
        'address': 207,
        'last_read_value': None,
        'name': 'AGC_GAIN_MAX'},

    216: {
        0: '',
        1: '',
        2: '',
        3: '',
        4: 'FD_TIME [7:0]',
        5: '',
        6: '',
        7: '',
        'address': 216,
        'last_read_value': None,
        'name': 'FD_TIME 1'},
    218: {
        0: '',
        1: '',
        2: 'FD_TIME [10:8]',
        3: '',
        4: '',
        5: '',
        6: '',
        7: 'FD_GAIN [7:3]',
        'address': 218,
        'last_read_value': None,
        'name': 'FD_TIME 2'},
}}